contiki-ng/cooja

apps/mspsim/README.md
apps/mspsim/build.xml

Updates the warning when MSPSim is not found to suggest a recursive submodule update. A non-resursive submodule update does not solve the issue when Cooja is used as a submodule itself.

Suggest a resursive submodule update when MSPSim is not found

---

java/org/contikios/cooja/CoreComm.java

Cooja tries to build the ContikiMote Java library first without and then with the Cooja JAR included in the class path. This results in a warning if it fails in the first try. This changes Cooja to try to compile the library both with current path and the Cooja JAR in the class path in a single step to avoid the compile warning. This should solve the issue reported in #3.

Only try to build ContikiMote Java library once.

---

apps/native_gateway/java/org/contikios/cooja/plugins/NativeIPGateway.java
apps/serial_socket/java/org/contikios/cooja/serialsocket/SerialSocketClient.java
apps/serial_socket/java/org/contikios/cooja/serialsocket/SerialSocketServer.java
java/org/contikios/cooja/contikimote/interfaces/ContikiRS232.java
java/org/contikios/cooja/dialogs/SerialUI.java
java/org/contikios/cooja/plugins/BufferListener.java
java/org/contikios/cooja/util/MoteSerialSocketConnection.java

No point restricting ourselves with 1kB. For instance, the buffer in `SerialSocketServer` was actually limiting the IP datagram length to 1024.

Increase the size of a number of buffers

---

config/external_tools.config
java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/CompileContiki.java
java/org/contikios/cooja/dialogs/ConfigurationWizard.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java

At the moment `obj_cooja` is hard-coded in multiple places.
This commit adds a configuration token called `PATH_CONTIKI_NG_BUILD_DIR` that can be set from the external dialog window. The configured value replaces all hard-coded instances of "obj_cooja".
We default to `build/cooja` if unconfigured. This pull is basically aimed at playing nicely alongside contiki-ng/contiki-ng#698

Make the output directory and library location configurable

---

apps/mrm/java/org/contikios/mrm/ChannelModel.java

This patch works around a race condition caused by simultaneous access to the ChannelModel module from the simulation and GUI threads.
It makes the method where the race condition occurs synchronized. When the MRM link visualizer is enabled in the GUI, the GUI thread calls to mrm.ChannelModel module which alters its state without any synchronization which causes a race condition and an exception that stops the simulation.
I consider it a workaround because, probably the whole module is not thread-safe and a nicer solution would be to refactor it. However, it fixes the issue.
To reproduce, use the attached CSC and binary. Select one of the nodes in the network window to display the link quality information. Start the simulation. An exception should happen in some time (usually within 3 …

Workaround a race condition in MRM channel model

---

java/org/contikios/cooja/contikimote/interfaces/ContikiEEPROM.java

The deprecated javax.xml.bind package was used for Base64 conversions in COOJA, but this functionality is existent in java.util.Base64. By changing this, we can now compile COOJA using newer Java versions.

Remove javax.xml.bind dependency 

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/plugins/Notes.java

When running on current Java versions, a null pointer exception occurs when opening a project because the default theme does not define the north pane, which is used in the Notes plugin.
This pull request addresses this issue in two ways: 
1) Add a try catch block in the Notes plugin to catch this exception.
2) Use `javax` nimbus look and feel instead of `com.sun.java`, which more JVMs should be able to locate.

Fix NullPointerException in Notes using default Look and Feel

---

java/org/contikios/cooja/Cooja.java

looks like imports PR#40 has break builds cooja in docker image , provided with contiki-ng .
there is returned in old API , that deprecated after JDK8

fix PR#40 vs JDK8 on contiki-ng docker container.

---

java/org/contikios/cooja/Simulation.java

This solves an issue modifying a simulation in Cooja that has been loaded in quickstart mode.

Only use quick start mode until simulation config been loaded

---

apps/avrora/src/org/contikios/cooja/avrmote/interfaces/MicaZID.java
apps/mspsim/src/org/contikios/cooja/mspmote/MspMoteTimeEvent.java
apps/mspsim/src/org/contikios/cooja/mspmote/interfaces/CC1101Radio.java
apps/mspsim/src/org/contikios/cooja/mspmote/interfaces/CC1120Radio.java
apps/mspsim/src/org/contikios/cooja/mspmote/interfaces/CC2520Radio.java
apps/mspsim/src/org/contikios/cooja/mspmote/interfaces/Msp802154BitErrorRadio.java
apps/mspsim/src/org/contikios/cooja/mspmote/interfaces/Msp802154Radio.java
apps/mspsim/src/org/contikios/cooja/mspmote/interfaces/MspSerial.java
apps/mspsim/src/org/contikios/cooja/mspmote/interfaces/TR1001Radio.java
apps/mspsim/src/org/contikios/cooja/mspmote/plugins/MspStackWatcher.java
java/org/contikios/cooja/EventQueue.java
java/org/contikios/cooja/MoteTimeEvent.java
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/TimeEvent.java
java/org/contikios/cooja/contikimote/interfaces/ContikiRS232.java
java/org/contikios/cooja/interfaces/ApplicationRadio.java
java/org/contikios/cooja/interfaces/Button.java
java/org/contikios/cooja/motes/AbstractWakeupMote.java
java/org/contikios/cooja/motes/DisturberMoteType.java
java/org/contikios/cooja/plugins/BufferListener.java
java/org/contikios/cooja/plugins/LogScriptEngine.java
java/org/contikios/cooja/plugins/skins/TrafficVisualizerSkin.java
java/org/contikios/cooja/radiomediums/AbstractRadioMedium.java

Implement EventQueue using java.util.PriorityQueue. There are three main benefits to this:
1. Improved performance for large networks (4x to 5x speed ups observed on large networks with 225 nodes). Performance for networks with a smaller number of nodes (49) remains similar to previous implementation.
2. Simulations run with the same seed will have the same output as the previous implementation.
3. TimeEvent no longer manages when it is next scheduled, preventing that time from being changed without it being updated in the EventQueue.

Use java.util.PriorityQueue to implement the EventQueue

---

config/corecomm_template.java
config/test_template.c
java/org/contikios/cooja/CoreComm.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/ConfigurationWizard.java

A Java long is 64 bits so use that
instead of Java int for addresses.
This patch requires an update of
the address parameters in the Cooja platform.c
in Contiki-NG.

Use jlong for addresses

---

apps/mspsim/src/org/contikios/cooja/mspmote/AbstractMspMoteType.java
apps/mspsim/src/org/contikios/cooja/mspmote/SkyMoteType.java
java/org/contikios/cooja/Simulation.java

The Contiki-NG regression tests makes Cooja
crash with a backtrace when Contiki-NG cannot
be compiled.
The user does not benefit from a stack trace of
Cooja in those scenarios so return an error instead
of crashing. The Contiki-NG regression tests still
fail, but with a reasonable error message.

Do not crash on compilation failure

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

The offset variable looks like it corresponds to a ptrdiff_t in C, so read it as an address instead of an int. The commit message that introduced the masking doesn't explain why, but I don't think that will improve the situation.

Read offset as address variable

---

build.xml

This target is not used anywhere in Contiki-NG
or Cooja so remove it. If the target should
exist, it should echo ${ant.java.version}
instead of starting the compiler.

build.xml: remove unused java_version target

---

.gitignore

This directory contains generated files
that should not be added to the repository.

Add javadoc to .gitignore

---

build.xml

The JVM option -d64 was removed in Java 10,
and Java 10 was end of lifed in March 2018.

build.xml: remove run64 target

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

Commit 96ea580dc76f8 missed this, use
parseUnsignedLong to avoid truncation issues.

Parse address as long instead of int

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/dialogs/MessageListText.java
java/org/contikios/cooja/plugins/LogScriptEngine.java
java/org/contikios/cooja/plugins/ScriptRunner.java

Remove the "Starting Cooja" message and
the "Message:" prefix on compilation output.
Put script status updates at debug level
since they are mainly for debugging Cooja
itself, the start/stop simulation messages
that immediately follow are typically more
interesting for the end user.

Make Cooja output less verbose

---

config/test_template.c

This function is required to return
the JNI version for the functions we
use, and we use some that are later
than 1.1. Without the function, the JVM assumes
JNI Version 1.1.
Java 11 is the oldest supported Java version
so make the function return JNI_VERSION_10.

config: add a JNI_OnLoad function

---

java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/plugins/LogScriptEngine.java

This makes it clear whether a test fails
or not by adding a "TEST FAILED" or "TEST OK"
message to the console log.
Also move the start simulation message to
debug level, the progress message from
LogScriptEngine is sufficient to understand
that the simulation has started.

Add log4j messages for test fail/ok

---

java/org/contikios/cooja/Cooja.java

The Contiki-NG regression tests are run with
-nogui and they all print out 5 lines of
"Visualized plugin was not started: ..".
This is not an error condition, so put this
message as a debug message to reduce the unimportant
output in the regression tests.

Make visualization logger info into debug

---

java/org/contikios/cooja/Simulation.java

Cooja logs the seed so add the simulation
name to that line of output. This allows us
to remove the corresponding echo from the
Contiki-NG test scripts.

Include simulation name when logging seed

---

java/org/contikios/cooja/interfaces/MoteAttributes.java

This is a local variable and StringBuilder
does not do synchronization like StringBuffer.

Use StringBuilder instead of StringBuffer

---

java/org/contikios/cooja/dialogs/CompileContiki.java

Add a variable $(CPUS) to commands that
is replaced with the number of cores,
so we can avoid spawning 40 compilers with
"make -j" in the Contiki-NG regression tests.
This gives a slight performance improvement
on 07-simulation-tests on my 12 core machine,
time -p make before the change:
real 174.78
user 339.52
sys 27.04
and after the change:
real 169.06
user 330.62
sys 26.70
Machines with fewer cores should see a greater
improvement.

Enable Cooja to pass core count to make

---

java/org/contikios/cooja/Cooja.java

Exit with error when trying to start the GUI
in a headless environment instead of printing
a long backtrace.
The headless situation occurs when DISPLAY is
missing on Linux.

Remove upstart crash when headless

---

build.xml

Ant currently exits with 0 when the run
target fails which makes it hard to detect
errors from the Contiki-NG build system.
Make ant fail when the run targets fail
instead.

build.xml: make run targets fail on error

---

java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/plugins/LogScriptEngine.java

The documentation for yield says:
It is rarely appropriate to use this method.
It may be useful for debugging or testing
purposes, where it may help to reproduce
bugs due to race conditions.
Beyond the anti-recommendation from the
documentation, we want to keep the thread
active so replace the yield with a short sleep
instead. Also remove the call to setPriority
and let the simulation thread keep the default
priority.
The net result seems to be a slight performance
improvement, using a precompiled jar and running
time -p make in 07-simulation-base in docker
before the change:
real 181.82
user 356.84
sys 30.90
and after:
real 175.49
user 342.36
sys 28.92

Stop interfering with thread scheduler

---

java/org/contikios/cooja/plugins/VariableWatcher.java

Replace two calls to String.format() with
a call to toString(), and pass in a long
value for the remaining call.

Stop passing objects to String.format

---

java/org/contikios/cooja/dialogs/CompileContiki.java

The Contiki-NG build system checks for
certain variables that might be present
during CI. Add these variables to
the environment when they are set.

Pass through Contiki-NG CI variables

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/CoreComm.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/contikimote/interfaces/ContikiRS232.java
java/org/contikios/cooja/dialogs/CompileContiki.java
java/org/contikios/cooja/dialogs/ConfigurationWizard.java
java/org/contikios/cooja/dialogs/MessageListUI.java
java/org/contikios/cooja/interfaces/ApplicationSerialPort.java
java/org/contikios/cooja/plugins/BufferListener.java
java/org/contikios/cooja/plugins/LogListener.java
java/org/contikios/cooja/plugins/LogScriptEngine.java
java/org/contikios/cooja/plugins/RadioLogger.java
java/org/contikios/cooja/plugins/ScriptRunner.java
java/org/contikios/cooja/plugins/TimeLine.java
java/org/contikios/cooja/util/StringUtils.java

Explicitly specify the charset as UTF-8 to
avoid relying on the JVM default charset.
The patch is compilation fixes on top of
an automatically generated patch by ErrorProne,
and ErrorProne shuffles the order of some
import statements.

Use UTF-8 as charset

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/CoreComm.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java

These give ErrorProne warnings and
are not hard to read without parentheses.

Remove superfluous parentheses

---

build.xml

Ant ignores the release tag when using
an old JDK to compile. Ensure a failure
by requiring the absence of a class that
was removed din Java 11.

build.xml: fail on Java < 11

---

.gitmodules

This enables having untracked files
in mspsim without "git status" in Cooja
showing the submodule as modified.

mspsim: ignore untracked changes

---

apps/mrm/build.xml

There is no ${jarfile}, replace it with
${mrm_jar} that exists.

mrm: fix clean rule in build.xml

---

java/org/contikios/cooja/interfaces/IPAddress.java

This should never overflow but the result
is a long so cast the variable before
multiplying.
This fixes a NarrowCalculation warning
in ErrorProne.

Perform calculation as long

---

tools/coffee-manager/build.xml

The jar target depends on the compile target, but
the faulty srcdir on the compile target makes
the jar target infer the files it needs and recompiles
them.

Fix coffee-manager build srcdir

---

java/org/contikios/cooja/Simulation.java

The event time is already logged and
EventQueue.Pair does not have a toString
method so log the event instead of
the entire pair.

Log the event instead of Pair@349803493

---

build.xml

The default maxmemory for Java 8 and later is 1G
for 32-bit server and 32G for 64-bit server.
The requirements for being considered a server are
modest by today's standards, 2 cores and 2G ram.
Remove the maxmemory fields on targets that have less
than 1G maxmemory.

build.xml: only set maxmemory > 1G

---

build.xml

Stop listing the transitive closure of
dependencies on each target and instead
depend on what it needs. Switch run targets
to use the jar file since they already
depend on jar, and remove the environment
setup.
This enables consolidating the two different
classpaths and removing the init target which
is not doing anything useful.

build.xml: use jar for run targets

---

java/org/contikios/cooja/Cooja.java

Lots of errors follow if specifiedCoojaPath does not
end with a /.

Ensure specifiedCoojaPath always ends with /

---

config/external_tools_win32.config
java/org/contikios/cooja/contikimote/ContikiMoteType.java

Windows uses && to execute nm twice. Move
the invocation of /bin/sh -c to the command
execution inside the Java code and avoid splitting
the command on space.
Also check the return value of the command.

Execute parse commands under /bin/sh -c

---

java/org/contikios/cooja/Cooja.java

The path already contains logger.error, add
a System.exit(1) after so the simulation does
not start with a different seed than the user
intended.

Fail when given a faulty seed

---

java/org/contikios/cooja/CoreComm.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/ConfigurationWizard.java

This ensures Cooja will either get a LibN.class
that corresponds to the freshly generated LibN.java,
or fail.
A secondary benefit is that Cooja will no longer
leave the "org" directory in the regression tests
in the Contiki-NG source tree.
This commit also fixes a bug where the return value
of the javac invocation was never checked.

Compile LibN.java in temporary directory

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/plugins/SimControl.java

The method is only called with the expected
parameters, it uses the same seed as the current
simulation, and it restarts if the simulation
is already running.
Remove the two parameters on the method,
and remove the single-parameter method
with the same name.

Remove one instance of reloadCurrentSimulation

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java

The firmware for Contiki motes is called mtypeNNN
where NNN is the mote identifier. The static method
getExpectedFirmwareFile returns something else,
and AbstractCompileDialog checks that this file exists.
The file no longer exists after the latest build system
updates, so make getExpectedFirmwareFile return the right
thing.
The make target name is constructed from the name
of the firmware file so that breaks from this fix.
Add a separate method that works like the old
getExpectedFirmwareFile and use that method for
constructing make target names.

Distinguish make target and library file names

---

java/org/contikios/cooja/Main.java

The picocli introduction transferred the test
from a deep nesting level in the old main method
and got the overall logic wrong, fix the condition.

Fix headless startup check logic

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Main.java

Remove the option to quickstart with anything other
than a Cooja simulation file, and provide a clear
error message when -nogui/-quickstart get the wrong
kind of file as argument.
This removes a number of special cases in the Cooja
startup code.

Remove quickstart option for C files

---

java/org/contikios/cooja/CoreComm.java

Convert methods to use try-with-resources, which simplifies the code flow. Also remove unused methods, make methods private, and inline a short method.

CoreComm cleanups

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

Make the space for mote names larger to reduce the risk
of collisions when reloading simulations. Before this,
reloading a simulation with 200 motes 5 times will
fill the available name space, and the next reload
will fail.

Reduce risk of name collision for ContikiMoteType

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/CompileContiki.java

The method is only used once and does not
belong in the dialogs package. Inline the method
in ContikiMoteType, which is closer to where
the method belongs.

Inline createCompilationEnvironment()

---

java/org/contikios/cooja/Cooja.java

Various changes that prepare for returning early without visualization in the Cooja constructor. The next step would be to move the early return, but ScriptRunner assumes there is a desktop and otherwise crashes.

More preparations for early return in Cooja constructor

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Main.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java

This makes it possible for the end-user to query
Cooja for what Contiki-NG build interface version
it is expecting.

Add build system info to cooja --version

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/plugins/ScriptRunner.java

This moves the early return without visualization
in the Cooja constructor even earlier.

Hoist early return in Cooja constructor

---

java/org/contikios/cooja/Mote.java
java/org/contikios/cooja/MoteInterface.java
java/org/contikios/cooja/MoteInterfaceHandler.java
java/org/contikios/cooja/MoteType.java
java/org/contikios/cooja/contikimote/ContikiMote.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/AddMoteDialog.java
java/org/contikios/cooja/motes/AbstractApplicationMote.java
java/org/contikios/cooja/motes/DisturberMoteType.java
java/org/contikios/cooja/mspmote/MspMote.java
java/org/contikios/cooja/mspmote/MspMoteType.java

The entirety of 07-simulation-base passes on Ubuntu 22.04
despite all the non-sky/z1 tests throwing an exception.
Let the error propagate to the top so the CI tests can
detect failures.

Return error when mote creation fails

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/serialsocket/SerialSocketServer.java
java/org/contikios/cooja/util/CmdUtils.java

Enable tests to run a series of commands after
the socket has started. This is immediately
useful for 17-tun-rpl-br, but it might come
in handy in other places too.

serialsocket: add a commands config option

---

.gitignore

Remove powertracker from .gitignore

---

build.xml

This removes a warning when using Gradle.

build.xml: rename "copy configs" task

---

java/org/contikios/cooja/mspmote/MspMoteType.java

Tell the user the name that will be used
for the firmware.

MspMoteType: give informational warning

---

java/org/contikios/cooja/mote/memory/SectionMoteMemory.java

Use collection methods when possible.
This avoids a log(n) lookup on each
key when copying, and shortens the code
for the lookup.

Optimize SectionMoteMemory

---

java/org/contikios/cooja/Cooja.java

Manipulate the in-memory XML representation instead of serializing to a string and perform regexp substitutions on that string.
A lot of whitespace changes, easiest to review commit by commit.

Refactor loadSimulationConfig

---

java/org/contikios/cooja/util/IPUtils.java

String.format is used for hex conversion of a short
and shows up in a profile. Use Integer.toHexString
instead.

Optimize getCompressedIPv6AddressString

---

java/org/contikios/cooja/plugins/ScriptRunner.java

The edit menu is empty, so remove it.

ScriptRunner: remove empty edit menu

---

java/org/contikios/cooja/plugins/ScriptRunner.java

Let the class hold a frame instead of
extending a frame. This is a step towards
avoiding to start the AWT thread in headless
mode.

ScriptRunner: internalize JInternalFrame

---

java/org/contikios/cooja/Cooja.java

The external tools user settings can not
be changed in headless mode, so move
the call inside the isVisualized() if-statement.

Only save settings upon changes

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java

Pass in a single parameter that contains
all the names that are reserved. This
avoids iterating over the already
active motes for each new name generated.

Simplify generateUniqueMoteTypeID

---

java/org/contikios/cooja/plugins/ScriptRunner.java

Spawning a JVM should not be the responsibility
of the ScriptRunner.
Beyond the conceptual issues, this will
use the JVM found in the path rather than
the JVM that is used by Cooja.
This also untangles doSaveConfig, so that
is now only called from Cooja.java.

ScriptRunner: remove run

---

java/org/contikios/cooja/Cooja.java

The user gets a dialog with a backtrace
if clicking on these menu items unless
they have a simulation available. Disable
the menu items without a simulation.

Disable plugins without simulation

---

java/org/contikios/cooja/Cooja.java

Make sure the file exists before trying
to read it, and do not save the file
if it is null.

Check externalToolsUserSettingsFile

---

java/org/contikios/cooja/Cooja.java

The method previously converted [CONFIG_DIR]
in the .csc file into the longer [CONTIKI_DIR]
when re-saving 02-ringbufindex.csc. This change
makes the shorter of the two paths the preferred
choice.

Prefer CONFIG_DIR over CONTIKI_DIR

---

java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/dialogs/ProjectDirectoriesDialog.java

The Cooja constructor will parse `cooja_default.config` and keep track of the mote types/radio mediums/etc that passed tryLoadClass(). Use this validated information instead of parsing the text file again and potentially get an immediate failure if the configuration is faulty.

Use validated information

---

java/org/contikios/cooja/contikimote/interfaces/ContikiRS232.java

Switch to a non-sychronized structure that has
a fast pop() method.

ContikiRS232: use ArrayDeque instead of Vector

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/plugins/LogScriptEngine.java

The more descriptive threadd names improved
readability for profiling, but chatty threads
disturb the log4j output. Shorten the names
of the threads that typically appear in
the output.

Shorten thread names

---

java/org/contikios/cooja/Cooja.java

This way of calling newInstance() apparently
gives better compiler checking, and is not
deprecated.

Cooja: replace call to deprecated method

---

java/org/contikios/cooja/Mote.java
java/org/contikios/cooja/mspmote/MspMote.java

The setType method was removed in b1efc97ba7cdf8e25afa6df130d7f365d2fe5701, so just remove the reference.

Fix broken javadoc references

---

java/se/sics/mspsim/core/AES128.java

Calling .toString() on an array will print
the object identity, not a human readable
form of its content. Replace with Arrays.toString()
instead.

AES128: stop using toString() on array

---

java/org/contikios/cooja/CoreComm.java

This might be the cause for setting the working
directory on the run targets in build.xml.
Gradle will be easier to integrate with this
change in the tree.

Use Cooja location for javac

---

java/org/contikios/cooja/mspmote/MspMoteType.java

The SecurityManager has been deprecated in Java 17
and will be removed in a future release. Remove
AccessControlException from the catch clause.

MspMoteType: remove AccessControlException

---

java/org/contikios/cooja/plugins/LogScriptEngine.java

This method shows up in the profiling data, so make it a bit faster by avoiding some recomputations and inlining the called method.

LogScriptEngine: speedup newLogOutput

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/MoteInterface.java

Making the arguments into an array is not
required.

Call varargs getConstructor()

---

java/org/contikios/cooja/Cooja.java

Return early in headless mode instead of
dereferencing null and catching the exception.

Cooja: do not dereference null

---

config/external_tools.config
java/org/contikios/cooja/plugins/Visualizer.java

Always register the skins that are
a part of Cooja. This makes the code
less dynamic which helps compilers
and code analysis tools to do a better
job.

Always register default skins

---

java/org/contikios/cooja/Cooja.java

Subclasses of VisPlugin are never loaded in
headless mode, so detect these classes early
and continue to the next class.

Cooja: avoid VisPlugin early when headless

---

java/org/contikios/cooja/plugins/LogScriptEngine.java

Move some code around in preparation for untangling interactions between threads.

Move code around in LogScriptRunner

---

.github/workflows/build.yml

The Gradle module provides all functionality
concerning caching, but by default, only jobs
on master will update the cache.
Allow pull requests to master to update the cache
so Gradle doesn't have to be downloaded in each CI
job.

CI: enable gradle cache

---

java/org/contikios/cooja/Cooja.java

This action is only required in visual mode,
so allocate it in the constructor along with
the rest of the GUI setup.

Cooja: privatize showQuickHelpAction

---

build.gradle

The new API works like a function would,
the previous API evaluates things in
the task body even when the task isn't used.

gradle: use new task API

---

java/org/contikios/cooja/CoreComm.java

Use the classpath for the current invocation
instead of trying to construct something from
the configuration.
This guarantees that the java file will compile
against the same classes that it will be loaded
with.

CoreComm: use current classpath

---

java/org/contikios/cooja/CoreComm.java

Move the increment of the file counter to ensure new names are used on each attempt to create a CoreComm. Also some minor code/comment cleanups.

Various CoreComm fixes

---

java/org/contikios/mrm/statistics/CDF_Normal.java

The author/version tags are not available
for methods.

CDF_Normal: fix javadoc warnings

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Simulation.java

Move the error check up to the place where it is required, tweak some method signatures, and stop pretending Cooja supports multiple `<simulation>` tags in the config.

Cooja: simplify loadSimulationConfig

---

java/org/contikios/cooja/plugins/ScriptRunner.java

The constructor knows if Cooja is visualized, so
put the SyntaxKit initialization in the code
that is only run when Cooja is visualized.

ScriptRunner: initialize SyntaxKit in constructor

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

This makes `parseStartAddrAndSize()` in MapSectionParser a single-pass operation. There are further optimization opportunities that are low hanging fruit, but start with this conservative optimization.
The OS X function is left with a FIXME so it can be updated after this has had some more testing.

Single-pass section start/address mapfile parsing on Linux

---

java/se/sics/mspsim/cli/CommandHandler.java
java/se/sics/mspsim/ui/ConsoleUI.java
java/se/sics/mspsim/ui/SerialMon.java

Make the fields that are synchronized on final
to ensure that all threads synchronize on the same
container.

Stop synchronizing on non-final fields

---

java/org/contikios/cooja/CoreComm.java

Cooja is compiled as Java 11 and javac on
LibN.java needs to produce a classfile of
the same version.

CoreComm: compile as java 11

---

java/org/contikios/cooja/mote/memory/Memory.java

Long is 32 bits on Windows and 64 bits on most other
64-bit platforms. Use the larger size since that
matches Linux/OS X.

Memory: update long size for 64-bit arch

---

java/org/contikios/cooja/motes/AbstractApplicationMote.java

The commit that added this line also added
a similar line to the MspMote constructor.
The line in the MspMote constructor has
already been removed by someone else.

AbstractApplicationMote: remove unused object

---

java/se/sics/mspsim/core/Timer.java

I am not sure if the comparison currently
works, but comparing the content is not
going to make the comparison fail more often.

Timer: compare arrays with Arrays.equal()

---

java/org/contikios/cooja/plugins/VariableWatcher.java

Fix the size of long, make the address box
use an address instead of a long, and fix
the widths to print enough for a 64-bit
hex value.

VariableWatcher: update for 64-bit machines

---

java/org/contikios/cooja/mote/memory/MemoryBuffer.java

Throw an exception when variable sizes are
unknown instead of assuming a size and continue.
This passes 07-simulation-base in the docker
container so these exceptions will probably
never be thrown.
Also fix a spelling error in the javadoc.

MemoryBuffer: throw on unknown variable sizes 

---

.gitignore

The docker image cannot save content
outside of the Contiki-NG repository.
Add an ignored directory for gradle home
so users can restart their containers
without having to download the dependencies
again.
This directory will also be used by
the Contiki-NG CI.

Add .gradle_home to gitignore

---

java/org/contikios/cooja/plugins/LogScriptEngine.java

Call stopSimulation() immediately when
testOK()/testFailed() are called.

LogScriptEngine: simplify shutdown logic

---

build.gradle
config/external_tools.config

Ant and Gradle needed to be in agreement
about the working directory during the migration
phase. Remove the workaround now since ant
is no longer a concern.

gradle: remove workingDir workaround

---

java/org/contikios/cooja/plugins/LogScriptEngine.java

Invoking stopSimulation from the simulation
thread just sets stopSimulation = false if
the simulation is running. Call it from
the current thread instead so the variable
gets set without waiting for the simulation
thread to process the poll requests.

LogScriptEngine: call stopSimulation directly

---

java/org/contikios/cooja/Cooja.java

These methods show up in profiles intermittently,
so do a single call and use that value.

Cooja: get plugin annotation once

---

java/org/contikios/cooja/Simulation.java

Calculate the runtime of the simulation
once, and then use and use the runtime
for calculating the speedup, rather than
calculating a new runtime for the ratio.
Remove the system time in milliseconds part
of the printout, if time should be printed
for informational purposes it should be
a human-readable readable form.
Also move the printout into the part that
leaves the event loop. This makes the runtime
calculation more precise, and avoids printing
the speedup message when exceptions were thrown.

Simulation: fix speedup printout

---

java/org/contikios/cooja/MoteInterfaceHandler.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java

Add a switch statement that recognizes the builtin
interfaces to avoid the slow tryLoadClass.

ContikiMoteType: hardcode internal interfaces

---

java/org/contikios/cooja/Cooja.java

Ensure GUI things run in the Swing thread.
Error handling can still be improved, but this hopefully stops the:
Unknown error: javax.swing.plaf.BorderUIResource cannot be cast to java.awt.Font
exceptions from happening in the first place.

Run GUI things in Swing thread

---

java/org/contikios/cooja/Cooja.java

Stop allocating (unused) observables in headless mode.
Allocate the menus in the Cooja constructor so they can be final fields.

Finalize fields and allocate less in headless mode

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

Assume size and start address are on the same line,
and only try to match the size when the start address
has matched. After that, stop the iteration.

ContikiMoteType: optimize mapfile parsing further

---

java/se/sics/mspsim/profiler/SimpleProfiler.java

The destination is a long so perform
the computation as a long, too.

SimpleProfiler: avoid int overflow

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Main.java

Add a synchronization between Cooja and
go() so the log4j resources in main can
be wrapped in a try-with-resources.

Close log4j logs properly

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Main.java

Cooja sometimes hangs after the latest
changes, so revert the patch that most
likely causes the issue.
This reverts commit 914ca495d47b54a4f317782e6f55aeea4db94f5c.

Revert "Close log4j logs properly"

---

java/org/contikios/cooja/contikimote/ContikiMote.java
java/org/contikios/cooja/motes/AbstractApplicationMote.java
java/org/contikios/cooja/mspmote/MspMote.java

Motes are created with respect to a simulation, so use the assignments in the constructor instead of reassigning values again.

Stop reinitializing motes in setConfigXML

---

java/org/contikios/cooja/Cooja.java

There are sanity checks in doRemoveSimulation()
so call it unconditionally. The check removed
by this commit must have been intended to be
mySimulation != null.

Cooja: check right variable

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java

The coreInterfaces field is only used to provide some visualization
for the end user about interfaces. Remove the field
and the methods for it. This removes the need for
reflection in ContikiMoteType.
This allows ContikiMoteCompileDialog to use
the default compileContiki() implementation.

ContikiMoteType: remove coreinterfaces + follow-on simplifications

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

This should not be used in a lot of places,
so inline it while we can.

ContikiMoteType: inline single-use field

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

The only use for this field is to output some
HTML for visualization purposes. Remove the
field since there is no code that updates
the content.

ContikiMoteType: remove display-only field

---

java/org/contikios/cooja/Cooja.java

Plugins add observers even in headless
mode which causes null pointer exceptions.
These checks should have been a part of
commit 7aec71070d3c57352714df3795395d8614d7f8af.

Cooja: add missing nullchecks

---

config/external_tools.config
java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java

This directory is decided by Contiki-NG,
so remove the option to configure it in
Cooja.

Remove PATH_CONTIKI_NG_BUILD_DIR

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

This untangles the setting of source files and firmware
files in different places.

ContikiMoteType: remove support for old Cooja mote

---

java/org/contikios/cooja/dialogs/AbstractCompileDialog.java

ContikiMoteType extends MoteID so include classes
that are derived in the check for what interfaces
that can be disabled.
Issue identified by Niclas Finne.

AbstractCompileDialog: keep ID and Position enabled

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/plugins/ScriptRunner.java

The simulator is allocated in go() so also
start the simulator there.
There are no strong guarantees for ordering
of plugins so starting the simulator in startPlugin()
is most likely wrong on a fundamental level.

Start simulator in go()

---

java/org/contikios/cooja/plugins/LogScriptEngine.java

Shorten the text message and remove the decimals
on the progress since they are always 0. This
avoids line wraps on a terminal with 80 columns.

LogScriptEngine: shorten info message

---

java/org/contikios/cooja/dialogs/AbstractCompileDialog.java

Loading a firmware immediately disables the just enabled
create button when the compile commands are blanked out.
Avoid updating the dialog status in the document listener
for that condition.

AbstractCompileDialog: stop disabling create button

---

java/org/contikios/cooja/mspmote/Exp5438MoteType.java
java/org/contikios/cooja/mspmote/SkyMoteType.java

Make all MSP430 mote types extend the same
class. This makes the image of the mote
appear in the mote information view.

Align Sky and Exp5438 with Z1

---

java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/dialogs/ImportAppMoteDialog.java
java/org/contikios/mrm/AreaViewer.java

Calling setFileFilter makes the filter active
so the interesting files are selectable, instead
of giving the option to enable the filter in
a drop-down.

Use FileFilter in dialogs

---

java/org/contikios/cooja/mspmote/plugins/MspCodeWatcher.java

Add quick help to describe how to build the motes with debug information. MspCodeWatcher requires this information to find the relevant source code files. Also, some code cleanup.

Add quickhelp to MspCodeWatcher plugin

---

java/org/contikios/cooja/plugins/ScriptRunner.java

The execute script action is not used, so
remove the configuration for it. Also use
the accessor from DefaultSyntaxKit for getting
the popup menu key.

ScriptRunner: remove unused menu configuration

---

java/org/contikios/cooja/plugins/ScriptRunner.java

The method is called from two places,
the first is the "Activate" menu item,
and the other is setConfigXML. Both
cases ensure that codeEditor.getText()
will contain the script.

ScriptRunner: stop needless reload

---

java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/mspmote/MspCompileDialog.java

The MspMote compile commands are platform neutral,
so move them into AbstractCompileDialog.

AbstractCompileDialog: provide default compile commands

---

java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java

Push the mote interface logic from the compile dialog
to the mote type itself. This change aligns ContikiMoteType
with MspMoteType in this respect.

Move getAllMoteInterfaceClasses to ContikiMoteType

---

java/org/contikios/cooja/Cooja.java

Push the assertion into the code that deals
with visual mode to avoid starting the AWT
thread in headless mode with assertions.

Cooja: avoid starting AWT thread

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

The map file name is only relevant for Linux,
so push the variable into the method that parses
the map file.

ContikiMoteType: localize mapFile variable

---

java/org/contikios/cooja/plugins/LogScriptEngine.java

The Cooja state might be in a bad shape if
the semaphores were not correctly reset. Throw
an exception to ensure things stop instead
of trying to recover and continue.

LogScriptEngine: make sem reset failure critical

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

CompileContiki.compile() will throw exceptions
when make fails, so this check can only detect
that the Contiki-NG build system is broken.
Remove the check since the Contiki-NG build
system is unlikely to be broken in this
particular way.

ContikiMoteType: remove file existence check

---

java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java

The dialog is called from ContikiMoteType, so moteType
can never be null.

ContikiMoteCompileDialog: remove spurious null check

---

java/org/contikios/cooja/plugins/SimControl.java

The run menu duplicates the functionality
of the buttons, but it takes longer to
click. Remove the run menu so it there
is only one user of the actions.

SimControl: remove the run menu

---

java/org/contikios/cooja/Cooja.java

Having "Simulation" under the "Simulation" menu
seems redundant. Rename the menu item to "Information"
to give a hint that the menu item displays the simulation
information.

Cooja: name SimInformation properly

---

java/org/contikios/cooja/Simulation.java

The variable is synchronized on pollRequests, so
add that in the remaining place where it is missing.

Simulation: synchronized access on hasPollRequests

---

java/org/contikios/cooja/Cooja.java

Cooja allocates mote types in multiple places,
update this caller for the additional constructor argument introduced in commit 69f6287d0891.

Cooja: fix creation of ContikiMoteType

---

java/org/contikios/cooja/Cooja.java

These fields are only relevant for graphical
Cooja, so put them in the class that needs
them.

Cooja: push fields to inner class

---

java/org/contikios/cooja/Cooja.java

Move code around so methods are only called once and code is as close as possible to where it is used.

Cooja: reorganize new simulation code

---

java/org/contikios/cooja/Cooja.java

Add the action listener and set the progress
dialog to visible after defining the worker thread, and do both in the AWT thread.

Cooja: delay showing of dialog

---

java/org/contikios/cooja/plugins/ScriptRunner.java

DefaultSyntaxKit binds control-R for "run", but
it cannot run the scripts from Cooja and the key
is already used by Cooja to reload simulations.
Remove the bind so Cooja can use it.

ScriptRunner: stop hooking control-R

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

This silences the echo commands for displaying
that the compiler and linker is executed.
This can be merged any time, but requires https://github.com/contiki-ng/contiki-ng/pull/2183 to have any practical effect.

Pass QUIET to build process

---

java/org/contikios/cooja/MoteInterfaceHandler.java

Add some classes that were not part of the list
of builtin interfaces.

MoteInterfaceHandler: extend interface cache

---

java/org/contikios/cooja/MoteInterfaceHandler.java
java/org/contikios/cooja/contikimote/ContikiMote.java

Turn the MoteInterfaceHandler into a holder
of information, and put the Polled*Ticks containers
and usage inside ContikiMote instead.

Move logic into ContikiMote

---

java/org/contikios/cooja/dialogs/AbstractCompileDialog.java

Disable the create button when running clean
since there is no firmware to load after that.

AbstractCompileDialog: clean disables create button

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/motes/AbstractApplicationMote.java
java/org/contikios/cooja/mspmote/MspMote.java

Motes can have the content of their
memory changed in runtime (that is what
tick() does), but not the memory itself.
Remove the unused methods.

Remove setMemory method

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/mspmote/MspMote.java
java/org/contikios/cooja/mspmote/MspMoteType.java

Remove an always-true null check, and iterate directly over a container instead of using an accessor.

Minor mote type adjustments

---

java/org/contikios/cooja/mspmote/AbstractMspMoteType.java
java/org/contikios/cooja/mspmote/Exp5438MoteType.java
java/org/contikios/cooja/mspmote/SkyMoteType.java
java/org/contikios/cooja/mspmote/Z1MoteType.java

This removes an IntelliJ warning about possible
heap pollution from parameterized vararg type.

MspMoteTypes: localize array creation

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java

Remove some dead code and inline the method at the single call site.

Simplify firmware name handling

---

java/org/contikios/cooja/Main.java
java/org/contikios/cooja/plugins/ScriptRunner.java

Stop generating COOJA.log unless the user specifies `-logname` when starting Cooja. Also refuse to start Cooja if the log directory cannot be created, instead of getting a fatal error after starting the simulation.

Tweak default logging behavior

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/motes/AbstractApplicationMote.java
java/org/contikios/cooja/mspmote/Exp5438Mote.java
java/org/contikios/cooja/mspmote/Exp5438MoteType.java
java/org/contikios/cooja/mspmote/MspMote.java
java/org/contikios/cooja/mspmote/MspMoteType.java
java/org/contikios/cooja/mspmote/SkyMote.java
java/org/contikios/cooja/mspmote/SkyMoteType.java
java/org/contikios/cooja/mspmote/Z1Mote.java
java/org/contikios/cooja/mspmote/Z1MoteType.java

Move code around so the MoteInterfaceHandler can be allocated in the constructor of the MSP430 motes.

Minor tweaks to MoteTypes

---

java/org/contikios/cooja/dialogs/AbstractCompileDialog.java

Check that the selected file is of the right type
before checking that the file exists. This avoids
spurious printouts on the console when no file
is selected.

AbstractCompileDialog: validate name before existence

---

java/org/contikios/cooja/dialogs/AbstractCompileDialog.java

Inline single-use variables, simplify logic, and remove unused return values, commented out code and always-true checks.

AbstractCompileDialog simplifications

---

java/org/contikios/cooja/Cooja.java

Put the code for creating motes inside the action. This revealed some spurious isVisualized checks, and the consolidation avoids calling stopSimulation multiple times when adding new mote types.

Cooja: consolidate mote creation code

---

build.gradle
java/org/contikios/cooja/Cooja.java

Use a property to decide if the AWT repainting
interception should be enabled. Gradle and Cooja
both seem to smush the console, so log the backtrace to the console.

Cooja: conditionally enable AWT debug code

---

java/org/contikios/cooja/Simulation.java

Remove unused methods, inline a single-use method, and remove the container that becomes unused from the removed methods.

Simulation simplifications

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java
java/org/contikios/cooja/mspmote/MspMoteType.java

Put the common code for MspMoteType/ContikiMoteType in a base class.
The code for compiling motes will also move into
this class, but that requires more than just
moving code so start with the simple parts.

Add a Contiki-NG base mote type

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/mspmote/MspMoteType.java

The Contiki-NG build system guarantees
the firmware will be produced if the build
was successful. Cooja will not get
to these points if make fails.

Remove spurious firmware existence checks

---

java/org/contikios/cooja/mote/BaseContikiMoteType.java
java/org/contikios/cooja/mspmote/MspMoteType.java

Commit b347506b17d7 added too eager error checking with compilation commands, there is no need to compile firmware-only simulations.
Restore the old logic and add a FIXME to combine
the two fields into a single field so the error
cases cannot happen.

MspMoteType: restore firmware-only support

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java
java/org/contikios/cooja/mspmote/MspMoteType.java

These methods are required for making generic
methods that work for any mote type.

Move name methods to BaseContikiMoteType

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java
java/org/contikios/cooja/mspmote/MspCompileDialog.java
java/org/contikios/cooja/mspmote/MspMoteType.java

ContikiMoteType uses special naming rules, so implement that as an override in ContikiMoteType itself.

Put firmware name logic in BaseContikiMoteType

---

java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
java/org/contikios/cooja/mspmote/MspCompileDialog.java
java/org/contikios/cooja/mspmote/MspMoteType.java

The initialization of target is getMoteType(),
so use that inside AbstractCompileDialog instead.

AbstractCompileDialog: remove target field

---

java/org/contikios/cooja/Cooja.java

Call the existing method for constructing
the configuration instead of duplicating
the code.

Cooja: use extractSimulationConfig

---

java/org/contikios/cooja/plugins/LogScriptEngine.java
java/org/contikios/cooja/plugins/ScriptParser.java

The NashornScriptEngine has a compile method
that is described as "allowing for efficient
precompilation and execution of scripts".
Use that method, which as an additional benefit
makes the entry point to the script explicit.

LogScriptEngine: compile script before running

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/plugins/LogScriptEngine.java

Make doQuit more robust against thrown exceptions and remove the spare exit thread in LogScriptEngine.

Remove one exit thread

---

java/org/contikios/cooja/plugins/LogScriptEngine.java

The method is never called when the simulation is running so remove the Runnable and make some simplifications to the time computations.

LogScriptEngine: remove Runnable + time simplifications

---

java/org/contikios/cooja/mspmote/MspMote.java

This just adds noise to the logs, the csc
file decides the name and the name of the csc
file is printed when the simulation starts

MspMote: remove log noise about firmware

---

java/org/contikios/cooja/plugins/LogScriptEngine.java

Limit the progress printout interval to 1 ms
of simulated time.

LogScriptEngine: only print progress every ms

---

java/org/contikios/cooja/plugins/TimeLine.java

The additonal information from the printout
is not actionable, so stop printing it.

TimeLine: remove zoom level printout

---

java/org/contikios/cooja/plugins/ScriptRunner.java

This makes it possible to switch from a file-backed script to the other kind of script without selecting one of the example scripts and then clear the code editor by hand.

ScriptRunner: add a "New" menu item

---

java/org/contikios/cooja/plugins/LogScriptEngine.java

There is only one call into these methods in LogScriptEngine so remove the code that guards against mis-usage of the API and ensure the call from ScriptRunner adheres to the invariants.

LogScriptEngine: simplify logic

---

java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/plugins/ScriptRunner.java
java/org/contikios/cooja/script/ScriptLog.java
java/org/contikios/cooja/script/ScriptMote.java
java/org/contikios/cooja/script/ScriptParser.java

This moves the LogScriptEngine to the cooja
package and its interfaces to cooja.script.
This will enable the simulation and script
engine to communicate directly without
switching threads and without requiring
synchronization.

Move LogScriptEngine to cooja package

---

java/se/sics/mspsim/platform/GenericNode.java
java/se/sics/mspsim/platform/sky/CC2420Node.java

Remove an unused method in CC2420Node, and then remove the unused field from the base class.

GenericNode: remove unused field

---

java/org/contikios/cooja/mote/BaseContikiMoteType.java

Run the compiler in the caller thread when
headless.
This change removes some old error message
propagation code which has no effect.

Compile in caller-thread when headless

---

java/org/contikios/cooja/dialogs/AbstractCompileDialog.java

The process can only be started by pressing
the button, and the button is disabled after
it has been pressed, so this call is not
required.

AbstractCompileDialog: remove no-op

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java
java/org/contikios/cooja/mspmote/MspCompileDialog.java
java/org/contikios/cooja/mspmote/MspMoteType.java

There is one functional change in this PR, only update source/firmware names after input has been validated in the SELECTED_FIRMWARE case.
The other changes do not change functionality, some method signatures are updated, some code is moved to inner classes, and various simplifications of statements.

AbstractCompileDialog: simplify/fix state update code

---

java/org/contikios/cooja/mote/BaseContikiMoteType.java

Commit 1250b345 introduced absolute paths
for the input files which was not what
getExpectedFirmwareFile was expecting.
Restore the previous behavior without
reverting the API changes so MSP430-based
motes can be created again.

Fix MSP430 compilation dialog

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/dialogs/AddMoteDialog.java
java/org/contikios/cooja/dialogs/BufferSettings.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
java/org/contikios/cooja/dialogs/CreateSimDialog.java
java/org/contikios/cooja/dialogs/ExternalToolsDialog.java
java/org/contikios/cooja/dialogs/ImportAppMoteDialog.java
java/org/contikios/cooja/dialogs/ProjectDirectoriesDialog.java
java/org/contikios/cooja/motes/ImportAppMoteType.java
java/org/contikios/cooja/mspmote/MspCompileDialog.java
java/org/contikios/cooja/mspmote/MspMoteType.java
java/org/contikios/cooja/mspmote/plugins/MspCodeWatcher.java
java/org/contikios/mrm/AreaViewer.java

This is a leftover from the applet support,
just put the Cooja.getTopParentContainer()
at the innermost constructor that needs it
instead.

Remove Container parameter from dialogs

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java
java/org/contikios/cooja/mspmote/MspCompileDialog.java
java/org/contikios/cooja/mspmote/MspMoteType.java

The functionality is already implemented for all
mote types, it just resides in the compile dialog. Move the code to the mote type where it belongs.

BaseContikiMoteType: add interface methods

---

java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/script/ScriptLog.java
java/org/contikios/cooja/script/ScriptParser.java

Change the return mechanism of scripts from
throwing exceptions even on successful exits
into being a regular return value that is
inspected upon return.
The implementation still uses exceptions inside
the script, but there is an outer catch that
converts the exception into a return value.
This also eliminates the need for spawning
a thread to exit Cooja in headless mode,
the script thread can just call doQuit after
it is done.

LogScriptEngine: shutdown without exceptions

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java

Push code around to reduce the side effects of getDefaultCompileCommands.

AbstractCompileDialog: detangle getDefaultCompileCommands

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java
java/org/contikios/cooja/mspmote/MspMoteType.java

Put the common configuration work in the base
class, and call that from the subclasses.
This means that ContikiMoteType will now accept
specifying compile commands with "command" instead
of "commands". The same thing happens for MspMoteType
that now accepts "contikibasedir", and gives an error
message when that is encountered. These elements
are never written by the respective mote types though,
so the leniency should not be a problem in practice.

BaseContikiMoteType: add setBaseConfigXML method

---

java/org/contikios/cooja/mspmote/Exp5438Mote.java
java/org/contikios/cooja/mspmote/Exp5438MoteType.java
java/org/contikios/cooja/mspmote/MspMote.java
java/org/contikios/cooja/mspmote/SkyMote.java
java/org/contikios/cooja/mspmote/SkyMoteType.java
java/org/contikios/cooja/mspmote/Z1Mote.java
java/org/contikios/cooja/mspmote/Z1MoteType.java

This moves all the initialization to the constructor of MspMote which shortens the code and simplifies the program flow. The change also enables making the CPU/memory fields final.

MspMote: initialize everything in constructor

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java

This enables storing the environment in a map,
so the flattening is no longer required.

BaseContikiMoteType: use ProcessBuilder for exec

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java
java/org/contikios/cooja/mspmote/MspCompileDialog.java
java/org/contikios/cooja/mspmote/MspMoteType.java

Package the mote configuration into a record
and pass that from the caller instead of having
the dialog querying the mote type to figure out
the configuration.

AbstractCompileDialog: pass mote config to constructor

---

java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java

Ensure the required parameters are allocated by the callers, and move out non-throwing code from the try-block.

Simplify compile()

---

java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java

Make the dialog big enough to avoid scrollbars for the interfaces by moving around some code. Also remove some dead code, inline some single-use methods, and pull more code into the constructor.

AbstractCompileDialog improvements

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java
java/org/contikios/cooja/mspmote/MspCompileDialog.java
java/org/contikios/cooja/mspmote/MspMoteType.java

This puts the plumbing in place for getting the configuration from the dialog with a MoteTypeConfig. Untangling the state inside AbstractCompileDialog is still challenging, so do that in future commits.

Make compile dialogs return MoteTypeConfigs

---

java/org/contikios/cooja/LogScriptEngine.java

Catch all exceptions in the thread and remove
the thread group that is only used to catch
exceptions.

LogScriptEngine: remove thread group

---

java/org/contikios/cooja/Cooja.java

Remove the printouts of external tools settings files. The OS-specific file cannot be altered by the user, and the user-specific file is used/changed by the GUI so the console printout is not useful.
These changes prints the simulation file/seed, the compilation, and then the simulation status/progress updates. An example output of this with `QUIET=1`:
```
INFO [main] (Simulation.java:385) - Simulation /home/user/contiki-ng/tests/07-simulation-base/02-ringbufindex.csc random seed: 1
> make TARGET=cooja clean
> make -j12 test-ringbufindex.cooja TARGET=cooja
INFO [main] (LogScriptEngine.java:238) - Script timeout in 10000 ms
INFO [sim] (LogScriptEngine.java:351) -  5% completed, 0.0 sec remaining
INFO [script] (LogScriptEngine.java:277) - TEST OK
INFO [sim] (Simulation.java:240) - Runtime: …
```

Cooja: remove external tools printouts

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/MoteInterfaceHandler.java
java/org/contikios/cooja/Simulation.java

MoteInterfaceHandler is not the perfect
place for mote type allocation, but
the other code that allocates other
things relating to motes already resides
there so group it together for now.

Allocate mote types in one place

---

java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/plugins/ScriptRunner.java

Ensure removeScriptEngine deactivates the script, reduce visibility of methods, and make the editor title reflect the actual activation status of the script.

Tweak script engine shutdown routine

---

java/org/contikios/cooja/serialsocket/SerialSocketClient.java

There is no point in doing the GUI setup
if the constructor will throw a runtime exception, so move that code early in the constructor.
This is a sibling of commit da948ce430563762.

SerialSocketClient: check mote serial port first

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/ProjectConfig.java

Propagate exceptions so Cooja stops upon failure in headless mode.
Also move the field with the file name from Cooja to ProjectConfig where it is used.

Stop after project parse error in headless mode

---

java/org/contikios/cooja/Cooja.java

Return true in headless mode when low
on memory.

Cooja: fix warnMemory return value

---

java/org/contikios/cooja/Cooja.java

Only use the explicit method when something
other than the default behavior is desired.

Cooja: use default stopSimulation method

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/Simulation.java

Add a blocking mode to startSimulation()
and call stopSimulation with the desired
return value from that.
This is preparation for being able to run
multiple simulations in a single Cooja
invocation.

Cooja: have main thread call doQuit

---

java/org/contikios/cooja/Simulation.java

Fast-forwarding the simulation time might
trigger the time-related asserts in the main
event loop.

Simulation: remove unused method

---

java/org/contikios/cooja/dialogs/MessageContainer.java

The startup code sets headless mode nowadays
so it is sufficient to check Cooja.isVisualized().

MessageContainer: remove spurious check

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Simulation.java

This moves the choice of default seed
from Simulation (which should not make
policy decisions) into Cooja.
The long term plan is to make the seed
final, but that requires CreateSimDialog
to not directly modify the simulation.

Simulation: pass seed to constructor

---

java/org/contikios/cooja/MoteInterfaceHandler.java
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/dialogs/CreateSimDialog.java

MoteInterfaceHandler is not the perfect
place for radio medium allocation, but
the other code that allocates other
things motes already resides there,
so group it together for now.
This commit also makes CreateSimDialog
return an error if the radiomedium could
not be allocated.

Allocate radio mediums in one place

---

java/org/contikios/cooja/script/ScriptParser.java

Make the YIELD function native and stop
renaming it in the ScriptParser.

ScriptParser: rename SCRIPT_SWITCH to YIELD

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/dialogs/CreateSimDialog.java

CreateSimDialog no longer pokes around in the internal state of the simulation after this commit.

CreateSimDialog: return config

---

java/org/contikios/cooja/dialogs/AddMoteDialog.java

Stop catching OutOfMemory exceptions, handle a positioner allocation failure gracefully by switching order of code, and various code cleanups.

AddMoteDialog: various simplifications

---

java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
java/org/contikios/cooja/mspmote/MspCompileDialog.java

Inline single-use methods, remove commented out code, and use lambdas in some places.

CompileDialogs: minor cleanups

---

config/external_tools.config
java/org/contikios/cooja/contikimote/ContikiMoteType.java

Older versions of readelf do not have the --sym-base option, so deal with the mixed output format.

ContikiMoteType: handle mixed readelf output

---

java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/script/ScriptParser.java

This simplifies the code, removes an IntelliJ
warning, and reduces the sys time slightly
on 07-simulation-base.
Before:
real 115.30
user 24.61
sys 3.35
After:
real 114.34
user 24.98
sys 2.81

LogScriptEngine: remove busy-wait loop

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

This PR fixes the following error I encountered when adding a Cooja mote to a simulation.
```
org.contikios.cooja.Cooja$SimulationCreationException: Unknown error: No line found
at org.contikios.cooja.Cooja.createSimulation(Cooja.java:3207)
at org.contikios.cooja.Cooja.loadSimulationConfig(Cooja.java:3109)
at org.contikios.cooja.Cooja$37.doInBackground(Cooja.java:2419)
at org.contikios.cooja.Cooja$37.doInBackground(Cooja.java:2404)
at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Th …
```

Fixes error "No line found"

---

java/org/contikios/cooja/script/ScriptParser.java

Remove the special startup-prelude and just
call YIELD() instead.

ScriptParser: call YIELD() on startup

---

java/org/contikios/cooja/script/ScriptParser.java

This makes the SEMAPHORE_SCRIPT into 1 when
exiting the script.

ScriptParser: release semaphore on exit

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/plugins/EventListener.java
java/org/contikios/cooja/plugins/MoteInformation.java
java/org/contikios/cooja/plugins/Visualizer.java

Hoist error checks to the beginning, use a switch-expression instead of a long if-then-else, and remove the Cooja parameter.

Cooja: simplify startPlugin

---

config/cooja_default.config
java/org/contikios/cooja/ProjectConfig.java

Put the two-line config file inside the Java code to eliminate a variety of possible failures that can happen when reading a file.

ProjectConfig: integrate default settings

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Simulation.java

Use a single thread instead of creating a new thread each time a simulation is started or stopped. This simplifies simulation control and avoids some issues when simulations are repetitively started and stopped very quickly.

Use a single thread for the simulation

---

java/org/contikios/cooja/Simulation.java

The call to stopSimulation when headless means
kill the simulation thread which corresponds
to what QUIT does.

Simulation: stop properly for headless mode

---

java/org/contikios/cooja/Simulation.java

This is preparation for making it possible
to prioritize actions by inserting elements
at the start of the command queue.

Simulation: use a deque

---

java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/Simulation.java

Move the log statements to the removal of
the simulation. This avoids noise on the console
in GUI mode, and makes 17-tun-rpl-br print
the test status when shutting down.

Always log test status in headless mode

---

java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/Simulation.java

Use a local variable instead to reduce interference between different LogScriptEngine instances.

LogScriptEngine: remove static variable

---

java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/serialsocket/SerialSocketServer.java

The second method is only called with false
as argument, so move the blocking to the
only caller that needs it.

Simulation: move blocking to first method

---

config/external_tools.config
java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java

This replaces the parsing of the map file
with checking a few special symbol names
in the output from readelf.

Use readelf for bss/data segment info

---

java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/script/ScriptLog.java
java/org/contikios/cooja/script/ScriptParser.java

The mote is available in the JavaScript code
so pass it as a parameter instead of digging
it out of the engine inside the called method.

ScriptLog: pass in mote as parameter

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Simulation.java

This is a more natural place for the
test printout, and the placement
ensures this is the last thing
printed for each simulation.

Move status printout to Cooja

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Main.java

The Cooja class does too many things,
so move the setting of look and feel
into the Main class.
This is also preparation for making
the -logname parameter more flexible
with multiple -nogui parameters.

Set look and feel in Main

---

java/org/contikios/cooja/Cooja.java

The second doQuit is only called with
the parameter false, so move that
part of the code to the first method.
This removes the non-shutdown actions
from the second doQuit.

Cooja: reorganize doQuit split

---

java/org/contikios/cooja/Simulation.java

The config files are not supposed to contain
duplicate IDs, so stop validating IDs and just
add to the container.
This reduces the risk of the concurrent modification exception seen in the Contiki-NG CI.

Simulation: load without searching for motes

---

java/org/contikios/cooja/Cooja.java

The shutdown hook stops the simulation,
so install it after project paths and
other basic things have been set up.

Cooja: install shutdown hook last

---

java/org/contikios/cooja/script/ScriptParser.java

Strings are immutable so use the string
directly instead of making a copy.
This saves 1 Mb of allocations on
02-ringbufindex.csc.

ScriptParser: stop copying messages

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/GUI.java
java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/Main.java
java/org/contikios/cooja/Simulation.java

This field is only used by the LogScriptEngine
in headless mode, so move the field from Cooja
to Simulation.
The reason the field was put in the Cooja class
in the first place was because of how the
initialization of Cooja looked at the time.

Move logDir field to Simulation

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/GUI.java
java/org/contikios/cooja/Main.java

This aligns the behavior of -quickstart
with -nogui. This also makes -update-simulation
work with the current test makefiles in Contiki-NG.

Allow multiple -quickstart

---

build.gradle
java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/CoreComm.java
java/org/contikios/cooja/Main.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java

Pass in the javac to use as a parameter
to ensure the intended compiler is used.
Also use the feature release of the JDK
as target when compiling CoreCommTemplate.java
instead of having a hardcoded version in
the source code.

Cooja: use same javac as gradle

---

build.gradle
java/org/contikios/cooja/CoreComm.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/corecomm/CoreCommTemplate.java

Move the memory copying from a JNI call to
Contiki-NG into Java.

CoreComm: implement getMemory/setMemory in Java

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Main.java

Add a vis field to the Config record
and make -nogui and -quickstart use
the same field for the filenames.

Cooja: restructure param handling

---

java/org/contikios/cooja/CoreComm.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java

Subtracting an offset at the caller and adding
it back in the callee just wastes cycles, remove
the offset calculations.

CoreComm: remove offset computations

---

build.gradle

According to https://picocli.info/#_closures_in_annotations, this can improve application startup time.

picocli: disable closures

---

java/org/contikios/cooja/plugins/ScriptRunner.java

The save code was written before the helper
method was created, utilize the helper
method since it exists.

ScriptRunner: use helper method

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Main.java

This adds the required infrastructure for
passing in options to simulations. There
is currently nothing that uses the options,
but this makes it easy to add consumers.

Add plumbing for per-simulation options

---

java/org/contikios/cooja/CoreComm.java
java/org/contikios/cooja/GUI.java
java/org/contikios/cooja/MoteType.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java

This removes the need for `setCompilationOutput` and `hasCompilationOutput` in the repository.

MoteType: add more constructors

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/plugins/Mobility.java

This PR adds support for the [Mobility Cooja plugin](https://sourceforge.net/p/contikiprojects/code/HEAD/tree/sics.se/mobility/) (see https://github.com/contiki-ng/cooja/issues/763).
How does it work?
The mobility plugin should be in the Tools menu. Click on it and load your positions.dat file. 
An example of the positions of a network with two mobile sensor nodes is shown below:
The format of the file is:
| Node ID      | Time (s) | x pos (m) | y pos (m)|
| ----------- | ----------- |---|---|
_**positions.dat:**_
0 0.0 0 0
1 0.0 30 30
0 1.0 0 10
1 1.0 30 20
0 2.0 10 10
1 2.0 20 20
0 3.0 10 0
1 3.0 20 30
0 4.0 0 0
1 4.0 30 30
The node IDs 0 and 1 correspond to node 1.0 and node 2.0 in Cooja, respectively.
The mobility plugin is from …

Support for Mobility plugin.

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Main.java

This option enables the user to automatically
start simulations loaded with -quickstart.
There is also a per-simulation option called
autostart, so
cooja --args="-quickstart=file1.csc -quickstart=file2.csc,autostart=true"
will first load file1.csc, and then load file2.csc and run the simulation.
Fixes #59.

Add an -autostart option

---

java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/mspmote/MspMote.java

Use types instead of string comparisons
to decide what happened in MSPSim.

MspMote: add a stop exception type

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/GUI.java
java/org/contikios/cooja/Main.java

Calling a method in GUI before log4j
is initialized makes info messages inside
the Cooja class to not appear. Curiously,
error messages still work.
Rather than investigating the exact
conditions, just put the look and feel
setup in Cooja again,

Set look and feel in Cooja again

---

java/org/contikios/cooja/Simulation.java

Only one element is required, so get that instead
of iterating over everything.

Simulation: get the element instead of iterate

---

java/org/contikios/cooja/Simulation.java

Shut down the script engine and everything
else nicely when the simulation gets
a RuntimeException.
This makes the current test fail, and
the remaining -nogui tests can run.

Simulation: quit nicely on exception

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/GUI.java

The recent changes that pushed more work
into the Simulation constructor enabled
pushing this to a place where it makes
sense to have the functionality.

Push setSimulation to inner scope

---

java/org/contikios/cooja/GUI.java

The plugin constructors contain Swing components
that need to be created in the AWT thread.

GUI: construct plugins from AWT thread

---

java/org/contikios/cooja/GUI.java

Move code around to avoid triggering
the IntelliJ empty catch-block warning.

GUI: fix empty catch-block warning

---

java/org/contikios/cooja/GUI.java

Clamp the size of the pane to prevent the time label to end up to the far right. Nimbus already behaves this way, but the system look and feel does not.

GUI: prevent right-alignment of time-label

---

java/org/contikios/cooja/Cooja.java

Initialize a member directly at declaration, and make the shutdown handler explicit in the constructor.

Cooja: simplify constructor

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java
java/org/contikios/cooja/motes/ImportAppMoteType.java
java/org/contikios/cooja/mspmote/Exp5438MoteType.java
java/org/contikios/cooja/mspmote/SkyMoteType.java
java/org/contikios/cooja/mspmote/Z1MoteType.java
java/org/contikios/mrm/AreaViewer.java

Use wrapper methods for creating URLClassLoader,
and get resources directly from the class. Getting resources from the class requires absolute paths,
so update the required image paths.

Remove direct classloader access

---

java/org/contikios/cooja/plugins/skins/TrafficVisualizerSkin.java

Make a copy of the list inside the critical section and iterate outside the critical section. Also inline some single-use variables.

TrafficVisualizerSkin: reduce synchronized section

---

java/org/contikios/cooja/Simulation.java
java/se/sics/mspsim/util/GDBStubs.java
java/se/sics/mspsim/util/NetworkConnection.java

These classes are not treated as an API that will be extended by a third-party so make the classes final to silence the IntelliJ warning about starting threads in the constructor. If someone wants to extend these classes in the future, they can remove the final.

Make some classes final

---

doc/ChangeLog.md
java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/GUI.java
java/org/contikios/cooja/PluginType.java
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/mspmote/plugins/MspCLI.java
java/org/contikios/cooja/mspmote/plugins/MspCodeWatcher.java
java/org/contikios/cooja/mspmote/plugins/MspCycleWatcher.java
java/org/contikios/cooja/mspmote/plugins/MspStackWatcher.java
java/org/contikios/cooja/plugins/BaseRSSIconf.java
java/org/contikios/cooja/plugins/BufferListener.java
java/org/contikios/cooja/plugins/DGRMConfigurator.java
java/org/contikios/cooja/plugins/EventListener.java
java/org/contikios/cooja/plugins/LogListener.java
java/org/contikios/cooja/plugins/Mobility.java
java/org/contikios/cooja/plugins/MoteInformation.java
java/org/contikios/cooja/plugins/MoteInterfaceViewer.java
java/org/contikios/cooja/plugins/MoteTypeInformation.java
java/org/contikios/cooja/plugins/Notes.java
java/org/contikios/cooja/plugins/PowerTracker.java
java/org/contikios/cooja/plugins/RadioLogger.java
java/org/contikios/cooja/plugins/ScriptRunner.java
java/org/contikios/cooja/plugins/SimInformation.java
java/org/contikios/cooja/plugins/TimeLine.java
java/org/contikios/cooja/plugins/VariableWatcher.java
java/org/contikios/cooja/plugins/Visualizer.java
java/org/contikios/cooja/serialsocket/SerialSocketClient.java
java/org/contikios/cooja/serialsocket/SerialSocketServer.java
java/org/contikios/mrm/AreaViewer.java
java/org/contikios/mrm/FormulaViewer.java

Put the plugin type in an enum inside the PluginType interface. This ensures that plugin type annotations do not cause runtime exceptions.

Make @PluginType() strongly typed

---

java/org/contikios/cooja/plugins/Visualizer.java

Calling invokeLater() in setConfigXML
makes it possible for Cooja to close
the simulation before the visualizer
has been loaded. This becomes a problem
with -update-simulation, that might drop
some visualizers along the way.
Plugins are now created from the AWT
thread, so remove the invokeLater call.

Visualizer: fix startup race condition

---

doc/ChangeLog.md
java/org/contikios/cooja/MoteType.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java
java/org/contikios/cooja/motes/AbstractApplicationMoteType.java
java/org/contikios/cooja/mspmote/plugins/MspCodeWatcher.java
java/org/contikios/cooja/plugins/Visualizer.java

Put the getters in BaseContikiMoteType instead,
and remove the setters completely.

MoteType: remove Contiki-NG-specific methods

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/GUI.java
java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/Main.java
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/serialsocket/SerialSocketServer.java

Add a SimConfig parameter to the load/create simulation functions that contains the information that is passed in separate parameters right now.
This does not make a huge difference right now, but it will simplify the handling of per-simulation configuration.

Consolidate sim config

---

java/org/contikios/cooja/Cooja.java

Remove the readonly attribute from user-specified
external tools files. This makes it possible for
the user to have separate external tools files
for different Coojas.

Cooja: enable multiple external tools settings

---

java/org/contikios/cooja/dialogs/ExternalToolsDialog.java

There is no possible code-sharing between these buttons so make separate action listeners for them. This removes the need for the logger.

ExternalToolsDialog: add separate action listeners

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Main.java

The config is persistent during the lifetime
of Cooja, so do not store the -nogui/-quickstart
information inside that.

Cooja: separate sim config files from cfg

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/GUI.java

The GUI methods are called from the AWT thread,
so move the EventQueue.invokeLater into Cooja
instead.

GUI: remove EventQueue.invokeLater wrapping

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/dialogs/ExternalToolsDialog.java

This array is only used in ExternalToolsDialog, so move it there.

Move externalToolsSettingsName to ExternalToolsDialog

---

java/org/contikios/cooja/Cooja.java

Declare the fields in the beginning of the class
and make them private when possible.

Cooja: move fields to top of class

---

java/org/contikios/cooja/GUI.java

These are two identical code blocks, put
them in a method and call that method instead.

GUI: split out common code

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java
java/org/contikios/cooja/mspmote/MspMoteType.java

Put <mote> inside <motetype> and make
the identifier an internal detail
of mote types.

Stop exposing motetype_identifier

---

build.gradle
doc/ChangeLog.md
java/org/contikios/cooja/Main.java

Rename the command line options to use a double
dash for long options.
Add temporary compatibility versions of parameters that are used by the Contiki-NG regression tests.
These can be removed after the submodule and Contiki-NG tests have been updated for the new names.

Use double dash in command line options

---

doc/ChangeLog.md
java/org/contikios/cooja/Main.java

There is no longer any need to specify `-nogui`/`-quickstart` for each simulation file as there is a separate argument to select between no GUI and GUI mode (`--[no-]gui`). The old arguments `-nogui`/`-quickstart` remain for backward compatibility.

Add option to specify simulation files as positional parameters

---

java/org/contikios/cooja/Cooja.java

Wrap every exception during simulation loading
inside a SimulationCreationException, so SwingWorker can give a retry/cancel-dialog.

Cooja: catch more exceptions to help SwingWorker

---

java/org/contikios/cooja/Cooja.java

Hoist the call to verifyProjects, so
reloading the current project does not
trigger warnings.

Cooja: only verify XML file input

---

java/org/contikios/cooja/motes/ImportAppMoteType.java

Cooja will never return null when getting the project classloader, so simplify the method.

ImportAppMoteType: simplify getParentClassLoader

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/GUI.java

There are null checks on the containers inside
GUI, so ensure we have a gui before trying to use
the containers.

Cooja: parse project config after GUI()

---

doc/ChangeLog.md
java/org/contikios/cooja/Main.java

The argument `--external_tools_config` specifies a configuration not only with user specified external tools, but also other user settings such as window location, file history, etc.

Rename argument external_tools_config to config

---

java/org/contikios/cooja/Cooja.java

These methods always return true, and
no caller checks the return value. Make
them return void instead.

Cooja: make register methods return void

---

java/org/contikios/cooja/Cooja.java

This tweaks the logic from commit f141dfd3fa3
so (0, 0) is permitted, but new simulations avoids a pile of windows near the center of the desktop.

Cooja: allow (0, 0) location

---

java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/Main.java

The Javadoc recommends using Path.of instead
of Paths.get since it might be deprecated
in a future release.

Use Path.of instead of Paths.get

---

java/org/contikios/cooja/plugins/MoteTypeInformation.java

Always use the observer for putting information in the content pane, and inline the single-use method inside the observer.

MoteTypeInformation: simplify implementation

---

java/org/contikios/cooja/Cooja.java

The same information is contained
in the message that is logged.

Cooja: remove debug printout

---

java/org/contikios/cooja/plugins/TimeLine.java

This makes the TimeLine able to find plugins
that are derived from LogListener.

TimeLine: use instanceof for plugin match

---

java/org/contikios/cooja/motes/AbstractApplicationMote.java

The observer is already added in the constructor.

AbstractApplicationMote: remove duplicate observer

---

java/org/contikios/cooja/ProjectConfig.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java

Replace the clone method with a copy constructor.
This fixes a couple of IntelliJ warnings, and
makes it possible to make some fields final.

ProjectConfig: make a copy constructor

---

java/org/contikios/cooja/Cooja.java

This avoids having to cast the result.

Cooja: use copy constructor instead of clone

---

java/org/contikios/cooja/radiomediums/DGRMDestinationRadio.java

This removes IntelliJ warnings about the clone
method.

DGRMDestinationRadio: remove unused clone method

---

java/org/contikios/mrm/ChannelModel.java

ChannelModel: use copy constructor

---

build.gradle

The directory was moved into config/
earlier.

gradle: remove old resource dir

---

java/org/contikios/cooja/SimEventCentral.java
java/org/contikios/cooja/Simulation.java

Simulation is the owner of the SimEventCentral object, so make a call to that instead of observing it.
Calling different methods when adding/removing motes eliminates the need to iterate over all motes to
figure out if the mote was added or removed.

SimEventCentral: remove mote count observer

---

doc/ChangeLog.md
java/org/contikios/cooja/RadioMedium.java
java/org/contikios/cooja/radiomediums/AbstractRadioMedium.java

The initial commit in 2006 had the JavaDoc
describe the radio medium as an interface,
and the current use supports that view, so
make the code reflect that intention.

RadioMedium: convert to interface

---

java/org/contikios/cooja/plugins/BaseRSSIconf.java

The plugin is only interested in when
motes are added/removed to the simulation,
so use a mote count observer on SimEventCentral
instead.

BaseRSSIconf: observe event central

---

java/org/contikios/cooja/Cooja.java

Selecting a window will deselect the other
windows automatically.

Cooja: stop deselecting windows

---

java/org/contikios/cooja/plugins/Notes.java

Occupy the space that was previously
used by the SimControl plugin.

Notes: fix spacing to visualizer

---

java/org/contikios/cooja/Simulation.java

The stop and quit commands are quite similar,
so doing stop before quit only introduces a delay
since it waits for the thread.

Simulation: remove stop on shutdown

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

The configuration is static so access
that through Cooja.configuration. This
removes an IntelliJ warning.
The change makes the Cooja parameter
unused in these functions, so remove that.

ContikiMoteType: remove unused parameter

---

java/org/contikios/cooja/radiomediums/AbstractRadioMedium.java

This prevents other objects from getting
direct access to the radio medium observable.
This is preparation for removing Observers/Observables.

AbstractRadioMedium: remove unused method

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java
java/org/contikios/cooja/motes/AbstractApplicationMoteType.java
java/org/contikios/cooja/motes/DisturberMoteType.java
java/org/contikios/cooja/motes/ImportAppMoteType.java
java/org/contikios/cooja/mspmote/MspMoteType.java

The visAvailable parameter is not required,
but keep it around until the interfaces need
to be changed.

MoteTypes: use Cooja.isVisualized

---

doc/ChangeLog.md
java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/SimEventCentral.java
java/org/contikios/cooja/plugins/LogListener.java
java/org/contikios/cooja/plugins/TimeLine.java
java/org/contikios/cooja/plugins/skins/LogVisualizerSkin.java

Adding/removing motes, and motes logging things
are unrelated actions. Decouple the interfaces,
so plugins can focus on the relevant information.

LogOutputListener: split in two interfaces

---

java/org/contikios/cooja/Simulation.java

Motes are removed on shutdown, so do the same
for mote types for consistency.
As a bonus, this silences an unused method
warning in IntelliJ.

Simulation: remove mote types on shutdown

---

java/org/contikios/cooja/Simulation.java

The other remove methods do not print
warnings, so remove this check and save
one full iteration of the container.

Simulation: remove spurious check

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Simulation.java

The message was printed first in the constructor
so it would be possible to pinpoint errors based
on the CI logs.
Move the message to the main loop instead, so creating a new simulation doesn't cause printouts to the console.

Move info log from Simulation to Cooja

---

java/org/contikios/cooja/Simulation.java

Exclude 0 from the sleep branch, and treat
the value like -1 in the other branch.
Besides not calling sleep(0), this change
should not make any difference.

Simulation: do not call sleep(0)

---

java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/mspmote/MspMote.java

This exception type can be used by other
emulators to stop the simulation, so
generalize it slightly and move it
to Simulation.

Move stop exception into Simulation

---

java/org/contikios/cooja/Main.java

Print the options in the order they are declared.
This is preparation for grouping the parameters
based on general category (Cooja options such as
--javac, simulation options such as --logdir/--autostart, and the rest such as --help and --version).

Do not sort --help output

---

java/se/sics/mspsim/core/RTC.java

Use a long constant to avoid sign-extension.

RTC: prevent sign-extension on constant

---

java/org/contikios/mrm/ChannelModel.java

The method getToRadio returns the receiver
in the implementations, so use that when
calculating the RX gain.

ChannelModel: fix RX gain

---

java/org/contikios/cooja/Main.java

The parseLong method returns a long, which
forces a call to longValue(), but that
gives a null pointer exception when
options.randomSeed is null.
Use Long.decode() instead since that returns
a Long.

Fix NPE in option decoding

---

java/org/contikios/cooja/LogScriptEngine.java

Add the listener in the constructor and remove
the listener when the Simulation is removed.

LogScriptEngine: add/remove listener once

---

java/org/contikios/cooja/MoteInterfaceHandler.java
java/org/contikios/cooja/contikimote/ContikiMote.java
java/org/contikios/cooja/motes/AbstractApplicationMote.java
java/org/contikios/cooja/mspmote/MspMote.java

Put the getConfigXML/setConfigXML methods in
MoteInterfaceHandler instead of having the same
code in every mote implementation.
This is tested by running --update-simulation on
07-simulation-base, and the simulation files are
unchanged.

MoteInterfaceHandler: add getConfigXML/setConfigXML methods

---

java/org/contikios/cooja/mspmote/MspMote.java
java/org/contikios/cooja/mspmote/MspMoteType.java

The mote type contains the firmware, so all motes
of that type have the same debug info. Share
that information between all motes instead of
reading it multiple times.

MspMoteType: move debug info to MspMoteType

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java
java/org/contikios/cooja/motes/AbstractApplicationMoteType.java

This unifies the identifier allocation for all mote types in the tree.

Base BaseContikiMoteType on AbstractApplicationMoteType

---

doc/ChangeLog.md
java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/GUI.java
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/plugins/Visualizer.java
java/org/contikios/cooja/util/EventTriggers.java

Replace the deprecated Observable with a typed replacement called EventTriggers. The replacement keeps track of the owner, so observers can easily remove all their triggers upon shutdown without needing to keep track of the triggers that were added.

Add a typed Observable replacement

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/GUI.java

The method has one caller and the arguments
are always the same, push that information
into the body of the callee.
Also remove the possibility for passing
in null to this method.

GUI: remove unused parameter

---

java/org/contikios/cooja/plugins/MoteInformation.java

This decouples the MoteTypeInformation plugin in preparation for eliminating observers of Simulation.

MoteInformation: remove type information button

---

java/org/contikios/cooja/GUI.java

Updating simulation files is usually not
done interactively, so avoid changing
the file history for the user.

Disable history with --update-simulation

---

java/org/contikios/cooja/Main.java

Add --print-contiki-ng-build-version and
--print-simulation-config-version. The
Contiki-NG build version is always printed
first when the two options are specified
in the same command line. An example for
script usage:
$ cooja -q --args="--print-contiki-ng-build-version --print-simulation-config-version" 2>/dev/null 2022071901
2022112801

Add print options for versions

---

java/org/contikios/cooja/contikimote/ContikiMote.java
java/org/contikios/cooja/motes/AbstractApplicationMote.java
java/org/contikios/cooja/motes/AbstractEmulatedMote.java

This is already inherited from AbstractWakeupMote.

Motes: remove spurious implements

---

java/org/contikios/cooja/Cooja.java

Removing this seems to save 1-2 seconds on
07-simulation-base.
Before:
real 78.07
user 1.44
sys 0.18
After:
real 77.23
user 1.32
sys 0.27
Cooja has 2 GB heap by default, so there
should not be a shortage of memory for
typical use. If Cooja still needs to
call System.gc() somewhere, it would
probably be better to do it last in
the simulation thread.

Cooja: stop calling System.gc()

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/GUI.java

This moves the dialog invocation from createSimulation into
GUI. The logic is clunky, but it removes GUI handling from
Cooja so it is a step in the right direction.

Move CreateSimDialog call to GUI

---

java/org/contikios/cooja/Watchpoint.java
java/org/contikios/cooja/motes/AbstractWakeupMote.java
java/org/contikios/cooja/mspmote/MspMote.java
java/org/contikios/cooja/mspmote/plugins/MspBreakpoint.java

The watchpoint functionality is almost completely generic, so move that to AbstractWakeupMote.
There is no generic breakpoint implementation in Cooja yet, so addBreakpoint() and setConfigXML() need to be implemented by all motes that want the functionality.
The getExecutableAddressOf() method also needs to be implemented, but that really belongs in MoteType.

Move WatchpointMote from MspMote to AbstractWakeupMote

---

java/org/contikios/cooja/MoteInterfaceHandler.java

Use the default clock type when the specified
clock cannot be found. Required for changing
mote types when reconfiguring simulations.

MoteInterfaceHandler: add clock fallback

---

build.gradle

The Picocli manual strongly recommends
the annotation processor, mentioning that
it gives compile time error checking.

gradle: add picocli-codegen

---

java/org/contikios/cooja/Main.java

This makes it easier to distinguish
between info, warnings and fatal errors.
As an added benefit, the colors also
make the compilation commands stand
out since they are not colored.
Since color might not work for all terminals,
add an option to disable color.

Use color for the console log

---

java/org/contikios/cooja/Main.java

Short option names are sorted in unexpected
ways by Picocli. The help option is the only
short option in Cooja, and that is not used
a lot, so remove it.
This is preparation for grouping related
command line parameters in the output
from --help.

Remove short help option

---

java/org/contikios/cooja/mspmote/plugins/MspCycleWatcher.java

This updates on start/stop of the simulation,
so use the event triggers for that instead.

MspCycleWatcher: remove observer

---

java/org/contikios/cooja/mspmote/plugins/CodeVisualizerSkin.java

This updates on start/stop of the simulation,
so use the event triggers for that instead.

CodeVisualizerSkin: remove observer

---

java/org/contikios/cooja/Simulation.java

There are no in-tree observers left,
so remove Observable.
It is possible that more things should
have event triggers in Simulation, but
that should be handled in a separate
commit.

Simulation: remove observable

---

java/org/contikios/cooja/motes/AbstractEmulatedMote.java
java/org/contikios/cooja/mspmote/MspMote.java

Move the support methods for breakpoints into
AbstractEmulatedMote. This is preparation for
adding a generic Breakpoint type.

Move signalBreakpointTrigger to AbstractEmulatedMote

---

java/org/contikios/cooja/MoteInterfaceHandler.java

These are used by 01-hello-world-sky.csc.

MoteInterfaceHandler: add missing interfaces

---

java/org/contikios/cooja/Simulation.java

Avoid reading the annotation unless it matters.

Simulation: read annotation when required

---

java/org/contikios/cooja/plugins/skins/AddressVisualizerSkin.java

This is the menu item name used by the visualizer, so align it with the other skin names.

AddressVisualizerSkin: tweak description

---

java/org/contikios/cooja/GUI.java
java/org/contikios/cooja/dialogs/AddMoteDialog.java

Put the Cooja state handling in GUI instead
of in the dialog.

AddMoteDialog: decouple from simulation

---

java/org/contikios/cooja/Breakpoint.java
java/org/contikios/cooja/mspmote/plugins/MspBreakpoint.java

The subclasses need to initialize before
createMonitor is called, so move that
call from Breakpoint to MspBreakpoint.

Breakpoint: move call to MspBreakpoint

---

doc/ChangeLog.md
java/org/contikios/cooja/SimEventCentral.java

Use simulation.getMoteTriggers().addTrigger()
instead.

SimEventCentral: remove MoteCountListener

---

java/org/contikios/cooja/GUI.java

Stop iterating when the user presses cancel,
rather than showing the next dialog.

GUI: fix cancel on sim reconfiguration

---

java/org/contikios/cooja/MoteInterfaceHandler.java
java/org/contikios/cooja/motes/AbstractWakeupMote.java
java/org/contikios/cooja/mspmote/MspMote.java

The mote type already contains a list of
the classes, query that instead of loading
something dynamically.

MoteInterfaceHandler: query mote type for class

---

java/org/contikios/cooja/GUI.java

Add the mote type description to the text
in the dialog that changes mote type on
reconfiguration.
This makes it apparent that the question
is asked once for each different mote type.

GUI: provide description on reconfiguration

---

java/org/contikios/cooja/MoteInterfaceHandler.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java

There is a single caller to getInterfaceClass,
so inline that method at the caller.
This moves the map of builtin interfaces from
MoteInterfaceHandlder to BaseContikiMoteType
where it belongs.

Move builtinInterfaces to BaseContikiMoteType

---

java/org/contikios/cooja/WatchpointMote.java
java/org/contikios/cooja/mspmote/MspMote.java

The method is in the mote, so stop passing
in a mote and casting the argument.

WatchpointMote: remove useless argument

---

java/org/contikios/cooja/MoteInterfaceHandler.java
java/org/contikios/cooja/motes/AbstractWakeupMote.java
java/org/contikios/cooja/mspmote/MspMote.java

Allow the caller to specify if failure should
be permitted. Also downgrade the fatal to warn
since the loading might continue after the message.
This fixes reconfiguring old csc files, for example rpl-udp-cooja.csc.

MoteInterfaceHandler: make failure conditional

---

java/org/contikios/cooja/Simulation.java

Set quick before creating radio mediums, since they might query for the status of quick during creation.

Simulation: set quick early

---

java/org/contikios/cooja/SafeRandom.java
java/org/contikios/cooja/Simulation.java

SafeRandom is only created in one place,
and setSeed is only called directly
after that. Move the call to setSeed
into the SafeRandom constructor instead.

SafeRandom: set seed at construction

---

java/org/contikios/cooja/plugins/EventListener.java

Use a LinkedHashSet to get a set of interfaces
with a predictable iteration order.

EventListener: simplify interface detection

---

java/org/contikios/cooja/MoteInterfaceHandler.java

Iterate over the interfaces that are immediately
available rather than asking the mote type for
a collection of Class<? extends MoteInterface>
that needs to be matched against what is currently available.
This is just a code reshuffle and asking different containers for the same information, no functional change.

MoteInterfaceHandler: simplify setConfigXML

---

java/org/contikios/cooja/dialogs/AbstractCompileDialog.java

Selecting a firmware should not enable the button
that performs make clean.

AbstractCompileDialog: fix clean button state

---

java/org/contikios/cooja/Cooja.java

There is only one config per plugin,
so call getChild instead of getChildren.

Cooja: remove spurious loop

---

java/org/contikios/cooja/contikimote/ContikiMote.java

Using forEach collapses profiling
output into the same category.
Use the longer code to get a more
readable profile output.

ContikiMote: stop using forEach

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/ExtensionManager.java
java/org/contikios/cooja/Simulation.java

This ensures that the simulation only loads registered plugins, and gives a placeholder for other methods relating to "dynamic" loading and querying of things.
Measurements are noisy (not because of this PR), but I get roughly a ~1% performance improvement on 07-simulation-base with this PR.

Simulation: only load registered plugins

---

java/org/contikios/cooja/CoreComm.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/corecomm/CoreCommTemplate.java

Using the new FFI made this class
tiny, so convert it to an interface.

CoreComm: convert to interface

---

java/org/contikios/cooja/mspmote/Exp5438Mote.java
java/org/contikios/cooja/mspmote/MspMote.java
java/org/contikios/cooja/mspmote/MspMoteMemory.java
java/org/contikios/cooja/mspmote/MspMoteType.java
java/org/contikios/cooja/mspmote/SkyMote.java
java/org/contikios/cooja/mspmote/Z1Mote.java

This aligns the symbol map handling with
SectionMoteMemory, and avoids regenerating
the symbols for each call to getSymbolMap().

MspMoteMemory: take a symbol map

---

java/org/contikios/cooja/MoteInterfaceHandler.java
java/org/contikios/cooja/script/ScriptMote.java

There is nothing that ensures a log and a serial port are the same thing, so add an API to get the serial port and use that.

ScriptMote: use API to get serial port

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/GUI.java
java/org/contikios/cooja/SupportedArguments.java
java/org/contikios/cooja/plugins/Visualizer.java
java/org/contikios/cooja/util/Annotations.java

Do not add plugins that are incompatible with
the radio medium to the tools menu.
This removes the DGRMConfigurator from the
Tools menu for incompatible radio mediums.

GUI: hide incompatible plugins in tools menu

---

java/org/contikios/cooja/contikimote/interfaces/ContikiRadio.java
java/org/contikios/cooja/interfaces/ApplicationRadio.java
java/org/contikios/cooja/radiomediums/AbstractRadioMedium.java
java/org/contikios/cooja/radiomediums/LogisticLoss.java
java/org/contikios/cooja/radiomediums/UDGM.java
java/org/contikios/mrm/MRM.java

The method digs around in the memory on ContikiMote,
so it is more costly than the name suggests.

Use getChannel() fewer times

---

java/org/contikios/cooja/GUI.java

The thread will die silently if there is
a NumberFormatException or similar when
loading the simulation.

GUI: catch all exceptions in SwingWorker

---

java/org/contikios/cooja/mote/BaseContikiMoteType.java

This is required for getting diagnostics
in GUI mode when quick-loading simulations.

BaseContikiMoteType: add output to exception

---

java/org/contikios/cooja/LogScriptEngine.java

String.format is slow(ish), and the progress printing message only requires whitespace alignment+rounding. Do the same computation by hand instead to keep
String.format out of the performance profiling.

LogScriptEngine: optimize progress event

---

java/org/contikios/cooja/mspmote/Exp5438Mote.java
java/org/contikios/cooja/mspmote/Exp5438MoteType.java
java/org/contikios/cooja/mspmote/MspMote.java
java/org/contikios/cooja/mspmote/SkyMote.java
java/org/contikios/cooja/mspmote/SkyMoteType.java
java/org/contikios/cooja/mspmote/Z1Mote.java
java/org/contikios/cooja/mspmote/Z1MoteType.java

Call getEntries() from the MspMote constructor
instead of all the subclasses.
The reason to not push it further inwards
is for alignment between MspMoteMemory
and SectionMoteMemory.

MSP430 motes: push getEntries() inwards

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/mote/memory/ArrayMemory.java

Call the other constructor directly from
ContikiMoteType instead.

ArrayMemory: remove one constructor

---

java/org/contikios/cooja/interfaces/IPAddress.java

The methods will only do anything if the
address/size pairs are matched between
the add and remove calls.

IPAddress: remove the added monitors

---

java/org/contikios/cooja/LogScriptEngine.java

When time is rounded up (>= x.95), the progress
can print "x.10 sec remaining". Add ten tenths
to the seconds instead.

LogScriptEngine: fix progress printout

---

doc/ChangeLog.md
java/org/contikios/cooja/COOJAProject.java
java/org/contikios/cooja/ProjectConfig.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/ProjectDirectoriesDialog.java

This feature complicates both Cooja itself,
and the Contiki-NG build system.

ContikiMoteType: remove C_SOURCES support

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

The scanner uses regular expressions to parse
the next number, get the next token and parse
the number in ContikiMoteType instead.
When profiling, this change halved the number
of samples in the parsing code of the readelf
output.

ContikiMoteType: optimize readelf scanner

---

build.gradle
java/se/sics/mspsim/platform/GenericNode.java

Stop Gradle from changing working directory
when using gradle run.
This removes the need for absolute paths
passed command line options, so:
cooja --args="--no-gui 02-ringbufindex.csc"
works when standing in tests/07-simulation-base.

gradle: run from current working dir

---

java/org/contikios/cooja/SimEventCentral.java

This is a trigger that gets called for
every output, so there will never be
more than one element too many in the buffer.

SimEventCentral: convert while to if

---

java/se/sics/mspsim/Main.java

Allocate in-tree node types without reflection, and leave the old logic and reflection in place for unknown node types.

MSPSim: create in-tree node types without reflection

---

doc/ChangeLog.md
java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/SimEventCentral.java
java/org/contikios/cooja/plugins/LogListener.java
java/org/contikios/cooja/plugins/TimeLine.java
java/org/contikios/cooja/plugins/skins/LogVisualizerSkin.java

There are 4 users of the interface in the tree,
and they all implement an empty body for the
removed method.
Remove the method, so it becomes a
single-method interface.

Remove unused method from LogOutputListener

---

config/logback.xml
java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/Main.java
java/org/contikios/cooja/util/LogbackColor.java

Use a custom color scheme that is designed
to be readable on both a black and white console.

Highlight log output

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

Move some code around to prepare for only parsing the readelf output once.
This saves ~10% allocations on 27-cooja-rpl-tsch-orchestra-root-rule-storing.

ContikiMoteType: optimize symbol parsing

---

build.gradle
doc/ChangeLog.md

The hard coded configuration in `build.gradle` override any value set by the caller and the default, if unspecified, is `logback.xml` anyway.

Gradle: allow configuration of logback configuration file via system properties

---

java/org/contikios/cooja/mspmote/Exp5438MoteType.java
java/org/contikios/cooja/mspmote/SkyMoteType.java
java/org/contikios/cooja/mspmote/Z1MoteType.java
java/se/sics/mspsim/Main.java
java/se/sics/mspsim/platform/GenericNode.java
java/se/sics/mspsim/platform/esb/ESBNode.java
java/se/sics/mspsim/platform/jcreate/JCreateNode.java
java/se/sics/mspsim/platform/sentillausb/SentillaUSBNode.java
java/se/sics/mspsim/platform/sky/CC2420Node.java
java/se/sics/mspsim/platform/sky/MoteIVNode.java
java/se/sics/mspsim/platform/sky/SkyNode.java
java/se/sics/mspsim/platform/sky/TelosNode.java
java/se/sics/mspsim/platform/ti/Exp1101Node.java
java/se/sics/mspsim/platform/ti/Exp1120Node.java
java/se/sics/mspsim/platform/ti/Exp5438Node.java
java/se/sics/mspsim/platform/ti/Trxeb1120Node.java
java/se/sics/mspsim/platform/ti/Trxeb2520Node.java
java/se/sics/mspsim/platform/tyndall/TyndallNode.java
java/se/sics/mspsim/platform/wismote/WismoteNode.java
java/se/sics/mspsim/platform/z1/Z1Node.java

All subclasses of Chip, such as flash,
requires a cpu for construction. Factor
out the CPU creation, so SkyNode & friends
can get the flash as a parameter to the
constructor.

Factor out CPU creation from MSP430 motes

---

config/logback.xml

Having highlight span over %n makes gradle
sometimes bleed into log output.
Only highlight within the line, and add an annoying space at the end of the line so %n is detected.

logback: add space to prevent mixed output

---

java/org/contikios/cooja/mspmote/interfaces/MspSerial.java

Stop installing an event handler that is guaranteed to NPE, and stop storing the data when there is
no USART source.

MspSerial: fix a potential null-pointer exception

---

java/se/sics/mspsim/platform/esb/ESBNode.java
java/se/sics/mspsim/platform/jcreate/JCreateNode.java
java/se/sics/mspsim/platform/sentillausb/SentillaUSBNode.java
java/se/sics/mspsim/platform/sky/CC2420Node.java
java/se/sics/mspsim/platform/sky/MoteIVNode.java
java/se/sics/mspsim/platform/sky/SkyNode.java
java/se/sics/mspsim/platform/sky/TelosNode.java
java/se/sics/mspsim/platform/ti/Exp1101Node.java
java/se/sics/mspsim/platform/ti/Exp1120Node.java
java/se/sics/mspsim/platform/ti/Exp5438Node.java
java/se/sics/mspsim/platform/ti/Trxeb1120Node.java
java/se/sics/mspsim/platform/ti/Trxeb2520Node.java
java/se/sics/mspsim/platform/tyndall/TyndallNode.java
java/se/sics/mspsim/platform/wismote/WismoteNode.java
java/se/sics/mspsim/platform/z1/Z1Node.java

Move most of the code into the constructors of each node.
This is already almost a 400 line patch, so more changes coming in the next PR instead.

Move setupNodePorts into constructor

---

java/org/contikios/cooja/mspmote/MspMote.java

This code was apparently missed when
making all the other loggers static.

MspMote: make mlogger static

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/GUI.java

This is the preparation for the top commit of #918.

Prepare for using Java's ProgressMonitor

---

build.gradle

This is no longer needed without log4j.

gradle: remove multi-release from manifest

---

java/org/contikios/cooja/plugins/analyzers/IPHCPacketAnalyzer.java

The TTL is available, add it to the output.

IPHCPacketAnalyzer: add TTL to printout

---

java/se/sics/mspsim/chip/Beeper.java
java/se/sics/mspsim/chip/Button.java
java/se/sics/mspsim/chip/CC1101.java
java/se/sics/mspsim/chip/CC1120.java
java/se/sics/mspsim/chip/CC2420.java
java/se/sics/mspsim/chip/CC2520.java
java/se/sics/mspsim/chip/DS2411.java
java/se/sics/mspsim/chip/Enc28J60.java
java/se/sics/mspsim/chip/ExternalFlash.java
java/se/sics/mspsim/chip/Leds.java
java/se/sics/mspsim/chip/MMA7260QT.java
java/se/sics/mspsim/chip/SHT11.java
java/se/sics/mspsim/chip/TR1001.java
java/se/sics/mspsim/core/Chip.java
java/se/sics/mspsim/core/MSP430Core.java
java/se/sics/mspsim/platform/GenericNode.java

The method is not used, and a large share
of the implementations return either 0 or 1.
Remove the method.

Chip: remove unused getConfiguration

---

java/org/contikios/cooja/dialogs/JResourceChooser.java
java/org/contikios/cooja/plugins/ScriptRunner.java

Use a JFileChooser with a custom FileSystemView
to open resources, instead of the current hardcoded array of names.

ScriptRunner: use chooser dialog for examples

---

java/org/contikios/cooja/MoteInterfaceHandler.java
java/org/contikios/cooja/contikimote/ContikiMote.java
java/org/contikios/cooja/motes/AbstractApplicationMote.java
java/org/contikios/cooja/motes/AbstractEmulatedMote.java
java/org/contikios/cooja/motes/AbstractWakeupMote.java
java/org/contikios/cooja/mspmote/MspMote.java
java/org/contikios/cooja/plugins/BufferListener.java
java/org/contikios/cooja/plugins/MoteInformation.java
java/org/contikios/cooja/plugins/TimeLine.java

MoteInterfaceHandler cannot be allocated in AbstractWakeupMote for MspMotes, because mote interfaces (SkyFlash for example) get the CPU to find the flash.
Not sure how to get there long-term, but this reduces the number of places we allocate MoteInterfaceHandler in.

Create MoteInterfaceHandler earlier

---

java/org/contikios/cooja/mote/BaseContikiMoteType.java

Only load interfaces that are listed in the mote type. The code is still too permissive with mote interfaces that are a part of Cooja, but the code is better
than before.

BaseContikiMoteType: validate moteinterface on load

---

java/org/contikios/cooja/plugins/Visualizer.java
java/org/contikios/cooja/radiomediums/LogisticLoss.java
java/org/contikios/cooja/radiomediums/UDGM.java
java/org/contikios/mrm/MRM.java

The last thing the simulation thread does
is call radioMedium.removed(), and some
radio mediums will call
Visualizer.unregisterVisualizerSkin to
unregister the skin they have registered.
If Cooja is loading a new simulation while
this is happening, the new simulation might
fail to load its visualizer skin because
the old simulation removed the skin midway
through the load of the new simulation.
There is no way to get a handle of the current
visualizer, so just move the registration to
inside the Visualizer constructor to avoid
the issue for now.
Long term, skins should have a way to register
themselves without having to call static
methods in the Visualizer.

Visualizer: work around race condition

---

java/org/contikios/cooja/Cooja.java

Put back the builtin plugins into
the context menu in the network
visualizer.

Cooja: restore missing context menu

---

java/org/contikios/cooja/contikimote/interfaces/ContikiLED.java

This makes the numbers consistent
with leds-arch.c and contiki-conf.h
in Contiki-NG.

ContikiLED: fix led numbers

---

java/org/contikios/cooja/contikimote/interfaces/ContikiClock.java

The clock_time_t definition in Contiki-NG
has been "unsigned long", which is 32 bits
on most 32-bit architectures, and 64 bits
on most 64-bit architectures.
Assume people are running Cooja on 64-bit
machines for now, and read as a 64-bit
variable. There is a pull request for
Contiki-NG to make the Cooja platform's
clock_time_t an uint64_t, so this commit
will eventually become correct for 32-bit
machines as well.

ContikiClock: fix 64-bit variable size

---

.github/workflows/build.yml

The 22.04 release is 1+ year old by now,
and this is also what the Docker image for
Contiki-NG uses.

CI: run on Ubuntu 22.04

---

.github/workflows/build.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties

This release brings full support for Java 20.
The release notes also mention faster Java
compilation because Gradle keeps the compiler
daemons running between builds, so that will
hopefully help when working on Cooja.

gradle: upgrade to Gradle 8.3

---

.github/workflows/build.yml
build.gradle
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/corecomm/CoreCommTemplate.java

This is on top of #1302, but Github does not understand PRs on top of PRs.
Unsure if this should be merged, but the FFI has improved since Java 17 and is now up to a preview status rather than an incubator. Furthermore, Java 21 which will be released in a couple of months will have a similar API.
If this should be merged, the Java in the Docker container needs to be updated too.

Update to Java 20

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/LogScriptEngine.java
java/org/contikios/cooja/Main.java
java/org/contikios/cooja/Simulation.java
java/org/contikios/cooja/plugins/ScriptRunner.java

The ECMAScript 6 support in Nashorn is
not complete, but enable what is there
by default.
The previous behavior is still available
by passing in an empty string as parameter
to --nashorn-args.

Default to use ECMAScript 6

---

java/org/contikios/cooja/contikimote/interfaces/ContikiRadio.java

Reading variables is not free, so only
read them when we have to, and remember
the value that was read.

ContikiRadio: read variables once

---

java/org/contikios/cooja/Cooja.java

This was forgotten for the 4.9 release.

Update Cooja version to 4.9

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/contikimote/CoreComm.java

The FFI supports symbol lookup, so query
that for the segment info and remove
the special cases from the parsing code.

ContikiMoteType: query FFI for segment info

---

java/org/contikios/cooja/dialogs/AbstractCompileDialog.java

This interface is required for calculating
the next wakeup time for motes.

AbstractCompileDialog: keep clock interface

---

build.gradle
java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/GUI.java
java/org/contikios/cooja/Main.java

Add a command-line option to select look and
feel, but continue to use Nimbus as default.
This allows us to remove the fallback code
for setting look and feel, so the user either
gets what they requested, or a failure.
Setting dragMode leaves residue from the borders
when moving windows on OS X, so use the default
dragMode.

Cooja: add option for using FlatLaf

---

.github/workflows/build.yml

CI: stop installing gawk

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

This will enable the CI to avoid version checks
when the support in Contiki-NG has landed.

ContikiMoteType: pass through COOJA_CI

---

java/org/contikios/cooja/Cooja.java

Native Windows is not supported by Contiki-NG,
and has not been tested for a long time with Cooja, so remove the support.
Cooja can still be used with Windows through WSL2.

Remove Windows settings

---

.github/workflows/build.yml

Contiki-NG now supports overriding
the version check, so use that instead
of doing in-place editing of Makefile.

CI: override Contiki-NG version check

---

java/org/contikios/cooja/mote/memory/SectionMoteMemory.java

There is a single symbol map for the SectionMoteMemory, so use that and stop re-adding the same symbols
when adding sections.

SectionMoteMemory: avoid re-adding symbols

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java
java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
java/org/contikios/cooja/mote/BaseContikiMoteType.java

If mote interfaces are excluded, pass that
information on to the build system.
This is currently a no-op since it requires
support in the Contiki-NG build system.

ContikiMoteType: pass absence info to make

---

java/org/contikios/cooja/Cooja.java

Put the call to update the GUI status
inside the AWT thread. This ensures
events are ordered in a certain way.

Cooja: move GUI update call

---

java/org/contikios/cooja/contikimote/ContikiMoteType.java

This is a single-pass operation, the same symbol
should never be reported twice.
This saves a log(n) operation (contains)
from running one time for each line.

ContikiMoteType: insert symbol without check

---

.clang-format
.github/workflows/build.yml
build.gradle

This adds the build support for formatting-checks
in CI. Run with:
./gradlew spotlessCheck -PclangFormat=clang-format-15
to use a different clang-format binary.
No checks are enabled by default with the build commands
currently used by Contiki-NG and this repository.

gradle: add spotless plugin

---

.github/workflows/build.yml
build.gradle

Add ErrorProne support to the build system.
Keep disabled by default since it makes
the build significantly slower, but enable
ErrorProne in the CI.

build.gradle: add ErrorProne

---

java/se/sics/mspsim/core/DMA.java
java/se/sics/mspsim/core/Timer.java

Using bitwise-and on booleans is not
idiomatic, switch to && instead.

Use logical && on booleans

---

java/org/contikios/cooja/plugins/VariableWatcher.java

There is no @note tag, replace it with
a word instead.

VariableWatcher: fix javadoc tag

---

java/org/contikios/cooja/Cooja.java
java/org/contikios/cooja/ui/ColorUtils.java
java/se/sics/mspsim/Main.java
java/se/sics/mspsim/util/PluginRepository.java

Not all alphabets have lowercase characters
that give the expected results. Use a default
locale to avoid that issue.
https://errorprone.info/bugpattern/StringCaseLocaleUsage

Use toLower with a locale

---

build.gradle
java/org/contikios/cooja/plugins/PowerTracker.java
java/org/contikios/cooja/plugins/skins/AttributeVisualizerSkin.java
java/org/contikios/cooja/plugins/skins/TrafficVisualizerSkin.java

https://errorprone.info/bugpattern/UnnecessaryLambda
The fixed things happen once per simulation,
so performance differences are negligible.
This should also help with getting more readable
backtraces in case of exceptions being thrown.

Fix UnnecessaryLambda warnings

---

java/org/contikios/mrm/AngleInterval.java

Return false when comparing with something
that is not an AngleInterval.

AngleInterval: fix equals method

---

java/org/contikios/cooja/plugins/analyzers/IPHCPacketAnalyzer.java
java/se/sics/mspsim/core/Multiplier.java
java/se/sics/mspsim/core/Multiplier32.java

Use enhanced switch in places where it makes sense to do so.

Fix some IntelliJ warnings

---

.github/workflows/build.yml

Run ./gradlew build to run a step that
includes :spotlessJavaBuild for format
checks.

CI: run spotless as part of build

---

java/org/contikios/cooja/Cooja.java

This path is a real error, so log
it as such.

Cooja: log error as error

---

java/org/contikios/cooja/plugins/LogListener.java

This menu was removed in 3d2c758149,
put it back so the log window behaves
like any other editor-like window.

LogListener: re-enable context menu

---

build.gradle

Enable building a binary with corresponding
start script by calling "./gradlew distZip/distTar".

build.gradle: configure distributions plugin

---

build.gradle

`clang-format` for Spotless can be enabled by specifying `-PclangFormat=clang-format`.  `clang-format` generates too many warnings to be enabled by default with the current configuration and source code.

Make Spotless use of clang-format optional and disabled by default for now

---

java/se/sics/mspsim/chip/DS2411.java
java/se/sics/mspsim/core/Flash.java

Fix errors from ErrorProne 2.26.1 about use of enum.ordinal().

Remove use of enum ordinal

---

.github/workflows/build.yml

The macOS 14 runner is an M1 machine
according to:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
so use that and macOS 13 to get an Intel
runner.

CI: test on macOS/{Intel,M1}

---

java/se/sics/mspsim/util/NetworkConnection.java

Error Prone 2.33 adds a warning for Java Records that contains arrays.

Fix Error Prone warning in NetworkConnection
