contiki-ng/cooja

- java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
Background: 
Had som major issues trying to compile several different motes in Cooja on InstantContiki... Also had the same issue when reloading simulations several times... (Only using UI)
It seems to be related to that a new thread is started each time in the dialog.... 
This PR removes that and has been working for us for quite som time now...
> Fix Cooja UI freeze

- java/org/contikios/cooja/Cooja.java
Also added optional argument to specify the Cooja installation directory when starting Cooja as alternative to automatic resolve.
This addresses #34.
> Try to resolve Cooja installation directory from codebase.

- apps/mspsim/src/org/contikios/cooja/mspmote/MspMote.java
We measured the impact of the deviation parameter on the mote execution and found significant inaccuracies. These would only appear when LPM was enabled on the mote.
We identified the origin of these inaccuracies to incorrect estimation of the timeline increase in COOJA/MSPSIM when both clock deviation and LPM are involved.
This new implementation of the execution for MspMote can precisely reproduce the requested deviation with absolute clock drift error well below 1 ppm.
More details about this evaluation and the new implementation can be found in:
"Toward accurate clock drift modeling in Wireless Sensor Networks simulation"
https://doi.org/10.1016/j.comcom.2020.08.025
> Fix clock deviation in MspMote

- java/org/contikios/cooja/contikimote/ContikiMoteType.java
Addresses should never be negative, so use a method
that will throw an exception if that happens.
> Use parseUnsignedLong for addresses

- build.xml
This makes it impossible to forget updating
the classpath for some target.
> build.xml: consolidate classpath definition

- java/org/contikios/cooja/interfaces/Battery.java
This reduces the amount of noise from
ErrorProne.
> Remove unused logger

- java/org/contikios/cooja/interfaces/IPAddress.java
- java/org/contikios/cooja/plugins/Visualizer.java
- java/org/contikios/cooja/plugins/skins/TrafficVisualizerSkin.java
Patch generated by Google ErrorProne so
some out-of-order import statements
are shuffled.
> Use ArrayList instead of LinkedList

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/Simulation.java
Use valueOf() in a couple of places and change
a type signature from Long to long.
> Remove some explicit boxing

- java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
- java/org/contikios/cooja/dialogs/AddMoteDialog.java
- java/org/contikios/cooja/dialogs/ProjectDirectoriesDialog.java
- java/org/contikios/cooja/dialogs/SerialUI.java
- java/org/contikios/cooja/plugins/BufferListener.java
- java/org/contikios/cooja/plugins/Visualizer.java
- java/org/contikios/cooja/util/StringUtils.java
Fix the issues IntelliJ found with string comparisons, null values and setting a variable to the value it already had.
> Fixes to issues found by IntelliJ

- build.xml
Add the suppression for the nashorn removal warning
to our run targets so users don't have to see it.
> build.xml: suppress nashorn removal warning

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/Simulation.java
- java/org/contikios/cooja/dialogs/AddMoteDialog.java
- java/org/contikios/cooja/interfaces/MoteAttributes.java
- java/org/contikios/cooja/plugins/RadioLogger.java
- java/org/contikios/cooja/plugins/TimeLine.java
- java/org/contikios/cooja/util/ExecuteJAR.java
This shortens the code and makes it obvious that
the iteration is over the entire collection.
> Avoid using index-based for-loops

- java/org/contikios/cooja/Cooja.java
Move some code around to share more of the Cooja
initialization code.
> Allocate frame in a single place, NFC

- java/org/contikios/cooja/Cooja.java
These are leftovers from the applet code.
> Simplify isVisualized(), NFC

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/dialogs/CompileContiki.java
The support for cygwin has been removed from
Contiki-NG.
> Remove cygwin support

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/contikimote/interfaces/ContikiPIR.java
- java/org/contikios/cooja/contikimote/interfaces/ContikiVib.java
- java/org/contikios/cooja/dialogs/AddMoteDialog.java
- java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
- java/org/contikios/cooja/dialogs/MessageListUI.java
- java/org/contikios/cooja/dialogs/ProjectDirectoriesDialog.java
- java/org/contikios/cooja/dialogs/SerialUI.java
- java/org/contikios/cooja/dialogs/UpdateAggregator.java
- java/org/contikios/cooja/interfaces/Button.java
- java/org/contikios/cooja/motes/AbstractWakeupMote.java
- java/org/contikios/cooja/plugins/BufferListener.java
- java/org/contikios/cooja/plugins/DGRMConfigurator.java
- java/org/contikios/cooja/plugins/LogListener.java
- java/org/contikios/cooja/plugins/MoteInformation.java
- java/org/contikios/cooja/plugins/MoteInterfaceViewer.java
- java/org/contikios/cooja/plugins/Notes.java
- java/org/contikios/cooja/plugins/ScriptRunner.java
- java/org/contikios/cooja/plugins/SimControl.java
- java/org/contikios/cooja/plugins/TimeLine.java
- java/org/contikios/cooja/plugins/VariableWatcher.java
- java/org/contikios/cooja/plugins/Visualizer.java
- java/org/contikios/cooja/positioners/ManualPositioner.java
- java/org/contikios/cooja/radiomediums/AbstractRadioMedium.java
This saves ~200 lines of code. Conversion
done with the built-in IntelliJ refactoring.
> Convert short new Class { .. } to lambda

- java/org/contikios/cooja/Cooja.java
This code is nearly 10 years old and not
currently used by Contiki-NG.
> Remove support for old-style test script

- java/org/contikios/cooja/CoreComm.java
- java/org/contikios/cooja/contikimote/ContikiMoteType.java
- java/org/contikios/cooja/dialogs/CompileContiki.java
- java/org/contikios/cooja/motes/ImportAppMoteType.java
- java/org/contikios/cooja/radiomediums/DirectedGraphMedium.java
- java/org/contikios/cooja/util/ExecuteJAR.java
This is handled by the constructor nowadays.
> Remove initCause() on exceptions

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/CoreComm.java
- java/org/contikios/cooja/MoteInterface.java
- java/org/contikios/cooja/Positioner.java
- java/org/contikios/cooja/RadioMedium.java
- java/org/contikios/cooja/motes/ImportAppMoteType.java
These are varargs methods so call them as that.
> Remove redundant array creation

- java/org/contikios/cooja/Cooja.java
These two branches are now nearly identical, combine them.
> Combine quickstart/nogui startup paths

- apps/mspsim/src/org/contikios/cooja/mspmote/MspCompileDialog.java
- apps/native_gateway/java/org/contikios/cooja/plugins/NativeIPGateway.java
- java/org/contikios/cooja/contikimote/ContikiMoteType.java
- java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
No specific theme, just things I found while editing the file.
> Several small ContikiMoteType improvements

- java/org/contikios/cooja/contikimote/ContikiMoteType.java
- java/org/contikios/cooja/dialogs/CompileContiki.java
- java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
Align the code between ContikiMoteType and ContikiMoteCompileDialog. This will eventually enable us to privatize ContikiMoteType-internal variables in ContikiMoteType.
> Remove some nullchecks

- java/org/contikios/cooja/Cooja.java
Remove some unused things from the config loading in Cooja.
> Simplify Cooja config loading

- java/org/contikios/cooja/Cooja.java
This puts all the GUI configuration inside
the Cooja constructor. The constructor still
needs to be reshuffled so the GUI configuration
comes last, but that is for a later commit.
> Move createFrame into Cooja constructor

- java/org/contikios/cooja/Cooja.java
The return values from the register methods are not
checked so remove the reflection-based checks and
just add the classes to the containers.
This change only affects plugin developers that forget
to add the right constructor to their class. They
will get an error message when the loading fails
instead.
This fixes an ErrorProne error about not checking
the return value of getConstructor.
> Simplify the register methods

- java/org/contikios/cooja/Cooja.java
Convert code to use try-with-resources and update a throws clause to reflect the current state of the code base.
> Various small fixes

- java/org/contikios/cooja/contikimote/ContikiMoteType.java
- java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
- java/org/contikios/cooja/dialogs/CompileContiki.java
- java/org/contikios/cooja/mspmote/AbstractMspMoteType.java
- java/org/contikios/cooja/mspmote/Exp5438MoteType.java
- java/org/contikios/cooja/mspmote/SkyMoteType.java
Remove a parameter that always has the same value and remove an if-statement that is always false.
> CompileContiki simplifications

- java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
Hoist the environment setup so only
the UI updates are run in the Swing thread.
> Inline updateForSource()

- java/org/contikios/cooja/dialogs/SerialUI.java
This removes some recomputation and memory
allocation in dataReceived() without changing
any functionality.
Also add a FIXME with some notes so this
can be improved in the future.
> Optimize SerialUI performance

- java/org/contikios/cooja/contikimote/ContikiMoteType.java
These methods are on the critical path
and serves no purpose, inline them.
> Inline single-use private methods

- java/org/contikios/cooja/plugins/ScriptRunner.java
This should not be a public method,
inline it at the single call-site instead.
> ScriptRunner: inline single use method

- java/org/contikios/cooja/plugins/ScriptRunner.java
This makes the popup menu correspond to
the properties set in the initialization.
> ScriptRunner: fix codeEditor initialization

- java/org/contikios/cooja/interfaces/IPAddress.java
- java/org/contikios/cooja/plugins/BufferListener.java
- java/org/contikios/cooja/util/IPUtils.java
This is no longer supported by Contiki-NG.
> Remove IPv4 support

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/Simulation.java
- java/org/contikios/cooja/contikimote/ContikiMoteType.java
- java/org/contikios/cooja/dialogs/MessageListUI.java
- java/org/contikios/cooja/mspmote/interfaces/SkyCoffeeFilesystem.java
- java/org/contikios/cooja/plugins/LogScriptEngine.java
- java/org/contikios/cooja/serialsocket/SerialSocketClient.java
- java/org/contikios/cooja/serialsocket/SerialSocketServer.java
- java/org/contikios/cooja/util/CmdUtils.java
- java/org/contikios/mrm/AreaViewer.java
- java/se/sics/mspsim/platform/GenericNode.java
- java/se/sics/mspsim/ui/ConsoleUI.java
- java/se/sics/mspsim/util/GDBStubs.java
- java/se/sics/mspsim/util/NetworkConnection.java
- java/se/sics/mspsim/util/TSPTest.java
Named threads simplifies reading profiling
data.
> Name all threads

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/Main.java
Add an option to save the simulation files
without running the simulation.
The majority of this commit is a whitespace
change from adding one level of extra indentation
in loadSimulationConfig.
> Add update simulation option

- java/org/contikios/cooja/motes/AbstractApplicationMote.java
- java/org/contikios/cooja/mspmote/MspMote.java
This is a sibling to commit b1efc97ba7.
> Remove unused method

- java/org/contikios/cooja/contikimote/ContikiMoteType.java
This just moves some code around to prepare for reducing the number of times the map file is parsed.
> Preparation for single-pass mapfile parsing

- java/org/contikios/mrm/ObstacleWorld.java
- java/se/sics/mspsim/chip/AT45DB.java
- java/se/sics/mspsim/chip/CC2420.java
- java/se/sics/mspsim/chip/CC2520.java
- java/se/sics/mspsim/chip/I2CUnit.java
- java/se/sics/mspsim/cli/CommandHandler.java
- java/se/sics/mspsim/cli/DebugCommands.java
- java/se/sics/mspsim/core/ADC12.java
- java/se/sics/mspsim/core/ADC12Plus.java
- java/se/sics/mspsim/core/Chip.java
- java/se/sics/mspsim/core/Flash.java
- java/se/sics/mspsim/core/FlashRange.java
- java/se/sics/mspsim/core/GenericUSCI.java
- java/se/sics/mspsim/core/IOSegment.java
- java/se/sics/mspsim/core/IOUnit.java
- java/se/sics/mspsim/core/MSP430.java
- java/se/sics/mspsim/core/MSP430Core.java
- java/se/sics/mspsim/core/SFR.java
- java/se/sics/mspsim/core/Timer.java
- java/se/sics/mspsim/core/USART.java
- java/se/sics/mspsim/core/USCI.java
- java/se/sics/mspsim/extutil/highlight/Token.java
- java/se/sics/mspsim/ui/ConsoleUI.java
- java/se/sics/mspsim/util/ArrayFIFO.java
- java/se/sics/mspsim/util/Utils.java
Fix dangling javadoc comments, and grammar/typos in comments.
> Fix some javadoc issues

- java/se/sics/mspsim/cli/ExecCommand.java
- java/se/sics/mspsim/cli/FileTargetCommand.java
- java/se/sics/mspsim/cli/MiscCommands.java
- java/se/sics/mspsim/cli/ScriptCommand.java
- java/se/sics/mspsim/cli/StreamCommandHandler.java
- java/se/sics/mspsim/core/DisAsm.java
- java/se/sics/mspsim/emulink/EmuLink.java
- java/se/sics/mspsim/extutil/highlight/HighlightSourceViewer.java
- java/se/sics/mspsim/extutil/highlight/Scan.java
- java/se/sics/mspsim/util/IHexReader.java
- java/se/sics/mspsim/util/MapTable.java
This patch is automatically generated by ErrorProne.
> Read/write streams as UTF-8

- java/org/contikios/cooja/Cooja.java
Do not start the GUI stuff unless in visual
mode
> Avoid starting the AWT thread on exit

- java/org/contikios/cooja/contikimote/ContikiMoteType.java
This method appears in the profiling data,
inline it at the two callsites to enable
further optimizations in the future.
> ContikiMoteType: inline method

- build.gradle
Commit 8371451297f fixes the underlying issue.
> gradle: remove fulljar workaround

- java/org/contikios/cooja/Cooja.java
Pass in the config and let the loading code deal with that instead of having an activate parameter that only loads things partway.
> Perform full plugin configuration during load

- java/org/contikios/cooja/plugins/ScriptRunner.java
The method always deactivates the previous script
first, so put that code first in the method so
it runs unconditionally. After that, do an early
return if the call only wanted a deactivation,
otherwise do the activation.
This removes a self-recursive call of the method.
> ScriptRunner: simplify setScriptActive

- java/org/contikios/cooja/Cooja.java
There are two callers to this method, one
is go() that verifies the parameters, and
the other is doLoadConfigAsync that is called
from various menus.
Put the retry logic in doLoaddConfigAsync
instead since that is where these things can fail.
> Cooja: shrink doLoadConfig

- java/org/contikios/cooja/Cooja.java
Ensure this field is always initialized
in GUI mode, and otherwise null.
> Cooja: finalize quickHelpProperties

- java/se/sics/mspsim/core/Watchdog.java
This field is already initialized in
the superclass.
> Watchdog: remove duplicate variable

- java/org/contikios/cooja/mote/memory/SectionMoteMemory.java
Do simple arithmetic on the callsite instead
of doing a slow call to a method.
> SectionMoteMemory: inline inSection

- java/org/contikios/cooja/contikimote/ContikiMoteType.java
These are no longer accessed from other classes,
so make them private.
> ContikiMoteType: make fields private

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/plugins/TimeLine.java
There is already a check for isRunnning
inside stopSimulation so make the call
to stopSimulation unconditional.
> Call stopSimulation unconditionally

- java/org/contikios/cooja/mspmote/Exp5438MoteType.java
- java/org/contikios/cooja/mspmote/SkyMoteType.java
This is now handled by AbstractMspMoteType.
> MspMoteType: remove unnecessary code

- examples/project_new_plugin/java/MyDummyPlugin.java
- java/org/contikios/cooja/Simulation.java
This can be implemented more efficiently using a TimeEvent if needed.
> Remove unused MillisecondObserver

- java/org/contikios/cooja/plugins/ScriptRunner.java
Split some methods, and remove some spurious try/catch and null checks.
> ScriptRunner simplification

- java/org/contikios/cooja/plugins/ScriptRunner.java
The only state set by the engine constructor
is the simulation, and that is fixed for
the life time of ScriptRunner. Allocate
the engine once and use the same engine
for all activations/deactivations.
> ScriptRunner: allocate engine once

- java/org/contikios/cooja/plugins/ScriptRunner.java
This is preparation for making the editor behave like it would in an IDE.
No functional changes in this PR besides the added menu items.
> ScriptRunner: add "Open.." and "Save as..." menu items

- java/org/contikios/cooja/plugins/ScriptRunner.java
This is preparation for generalizing scriptrunner
to handle multiple scripts.
> ScriptRunner: create editor in separate method

- java/org/contikios/cooja/Cooja.java
This is preparation for putting the SimControl functionality in Cooja.
> Cooja: inline single-use methods

- java/org/contikios/cooja/Cooja.java
Allocate the filter when a new file chooser
is required.
> Cooja: localize SAVED_SIMULATIONS_FILES

- java/org/contikios/cooja/MoteInterface.java
- java/org/contikios/cooja/MoteInterfaceHandler.java
There is nothing dynamic with how MoteInterfaceHandler is used, so make the variables final and initialize them in the constructor.
> Move work to MoteInterfaceHandler constructor

- java/org/contikios/cooja/contikimote/ContikiMote.java
- java/org/contikios/cooja/motes/AbstractApplicationMote.java
- java/org/contikios/cooja/motes/AbstractEmulatedMote.java
- java/org/contikios/cooja/motes/AbstractWakeupMote.java
- java/org/contikios/cooja/motes/DisturberMoteType.java
- java/org/contikios/cooja/mspmote/MspMote.java
The simulation does not change during the lifetime of the mote, so make the field final.
> Remove setSimulation method in MoteType

- java/org/contikios/cooja/contikimote/ContikiMoteType.java
- java/org/contikios/cooja/mote/BaseContikiMoteType.java
- java/org/contikios/cooja/mspmote/MspMoteType.java
Use the same code for compiling in headless mode with MspMoteType and ContikiMoteType.
> Put headless compilation in BaseContikiMoteType

- java/org/contikios/cooja/contikimote/ContikiMoteType.java
- java/org/contikios/cooja/mote/BaseContikiMoteType.java
- java/org/contikios/cooja/mspmote/MspMoteType.java
ContikiMoteType displays a bit more information than the native nodes, so add a target-hook to fill in those parts.
> Move getTypeVisualizer to BaseContikiMoteType

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/mspmote/MspMoteType.java
- java/org/contikios/cooja/plugins/RadioLogger.java
This attribute is only set, never read,
so stop writing it.
> Remove unused EXPORT attribute

- java/org/contikios/cooja/Cooja.java
Do some simplifications in getPluginsConfigXML and then combine extractSimulationConfig and getPluginsConfigXML into a single method.
> Cooja: simplify extractSimulationConfig

- java/org/contikios/cooja/plugins/ScriptRunner.java
Remove the link script to file menu and corresponding
actions. This makes the ScriptRunner editor behave
like other IDEs, one uses save/open for dealing
with files.
> ScriptRunner: use save/open as regular IDEs

- java/org/contikios/cooja/dialogs/MessageListText.java
Call println directly instead of calling
a method that calls println.
> MessageListText: speedup add()

- java/org/contikios/cooja/Cooja.java
Most calls to doLoadConfig are constructed by an action running in the AWT thread, but some of that code creates  a new thread that then invokes invokeAndWait() on the AWT thread.
Move code around so the GUI is constructed without switching threads.
> Cooja: flip logic to run GUI in AWT thread

- java/org/contikios/cooja/plugins/ScriptRunner.java
Add a return value from activateScript
and check the return value in setConfigXML.
> ScriptRunner: add error check

- java/org/contikios/cooja/plugins/LogScriptEngine.java
- java/org/contikios/cooja/plugins/ScriptRunner.java
Put the harmless actions in the new method
compileScript, and keep the intricate things
like semaphores in activateScript.
This split makes it possible to rearrange
the ordering of activateScript in ScriptRunner,
but the new ordering makes it obvious that
it's possible to back out at a late stage.
> LogScriptEngine: split activateScript in two

- java/org/contikios/cooja/plugins/ScriptRunner.java
This does not change the logging behavior for
a single ScriptRunnner, as long as the log file
can be opened. If the log file cannot be
opened, this will throw an exception before
starting the simulation.
If there are multiple ScriptRunnners, the second
will log to COOJA-02.testlog, the third to
COOJA-03.testlog, and so on.
> ScriptRunner: log to separate files

- java/org/contikios/cooja/plugins/LogScriptEngine.java
- java/org/contikios/cooja/plugins/ScriptRunner.java
This makes ScriptRunner into the user
interface that deals with scripts,
and LogScriptEngine as the part that
runs the scripts and takes care of their
output.
> Move logWriter to LogScriptEngine

- java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
- java/org/contikios/cooja/mote/BaseContikiMoteType.java
- java/org/contikios/cooja/util/StringUtils.java
Add a new helper method for command line splitting and call that.
> StringUtils: add splitOnNewLine method

- java/org/contikios/cooja/dialogs/ExternalToolsDialog.java
Log an error to the console and fix some IntelliJ warnings.
> Various ExternalToolsDialog updates

- java/org/contikios/cooja/RadioMedium.java
- java/org/contikios/cooja/Simulation.java
- java/org/contikios/cooja/dialogs/CreateSimDialog.java
Wrapping newInstance() inside a static method
does not accomplish anything, inline the method
at the two callsites instead.
> RadioMedium: inline single-line method

- java/org/contikios/cooja/Simulation.java
This avoids comparing the same element over
and over again.
Also invert some if-statements to make early
returns since everything is already re-indented
in this commit.
> Simulation: use switch in setConfigXML

- java/org/contikios/cooja/LogScriptEngine.java
This code cannot really fail so put all
the calls to engine.put before creating
the script thread.
> LogScriptEngine: init engine in one place

- java/org/contikios/cooja/serialsocket/SerialSocketClient.java
- java/org/contikios/cooja/serialsocket/SerialSocketServer.java
This is a large whitespace change, hoist some null checks and remove always-true if-statements.
> Minor SerialSocket updates

- java/org/contikios/cooja/contikimote/ContikiMoteType.java
Put the command preparation before calling
loadCommandData so the method can be used
for other commands.
> ContikiMoteType: hoist command preparation

- java/org/contikios/cooja/mote/memory/MemoryInterface.java
The field is always initialized to null,
so remove it.
> Symbol: remove section field

- java/org/contikios/cooja/Cooja.java
Unclear why this field exists, the Cooja
pointer can be accessed through Cooja.this
in inner classes.
> Cooja: remove cooja field

- java/org/contikios/cooja/mspmote/MspMote.java
Push the check for deviation into the body of driftExecute and always use driftExecute for execution.
> MspMote: merge regularExecute and driftExecute

- java/org/contikios/cooja/Simulation.java
Throw an exception if the radio medium cannot
be loaded.
> Simulation: error on failed radio medium

- java/org/contikios/cooja/util/ArrayQueue.java
- java/se/sics/json/JSONArray.java
- java/se/sics/json/JSONObject.java
- java/se/sics/json/ParseException.java
- java/se/sics/mspsim/core/BreakpointException.java
- java/se/sics/mspsim/core/EmulationException.java
- java/se/sics/mspsim/extutil/highlight/LineNumberedBorder.java
- java/se/sics/mspsim/extutil/highlight/SyntaxHighlighter.java
- java/se/sics/mspsim/platform/AbstractNodeGUI.java
- java/se/sics/mspsim/platform/esb/ESBGui.java
- java/se/sics/mspsim/platform/jcreate/JCreateGui.java
- java/se/sics/mspsim/platform/sentillausb/SentillaUSBGui.java
- java/se/sics/mspsim/platform/sky/SkyGui.java
- java/se/sics/mspsim/platform/wismote/WismoteGui.java
- java/se/sics/mspsim/platform/z1/Z1Gui.java
- java/se/sics/mspsim/ui/CPUHeatMap.java
- java/se/sics/mspsim/ui/ChartPanel.java
- java/se/sics/mspsim/ui/ConsoleUI.java
- java/se/sics/mspsim/ui/ControlUI.java
- java/se/sics/mspsim/ui/DebugUI.java
- java/se/sics/mspsim/ui/StackUI.java
- java/se/sics/mspsim/util/DotDiagram.java
- java/se/sics/mspsim/util/ELFException.java
This has already been removed from most Cooja
classes so complete the removal.
> Remove serialVersionUID

- java/org/contikios/cooja/LogScriptEngine.java
Add exit value arguments for all error situations
that cause a shutdown.
> LogScriptEngine: simplify shutdown code

- build.gradle
- java/org/contikios/cooja/CoreComm.java
- java/org/contikios/cooja/contikimote/ContikiMoteType.java
- java/org/contikios/cooja/corecomm/CoreCommTemplate.java
Use the new foreign function interface in Java 17 to calculate offset.
> ContikiMoteType: use Java 17 FFI for offset

- java/org/contikios/cooja/script/ScriptParser.java
If there is a timeout and a shutdown at the same
time, return a timeout failure.
> ScriptParser: prefer timeout over shutdown

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/Simulation.java
Use Cooja.isVisualized() inside the body instead.
> Simulation: remove visAvailable parameter

- java/org/contikios/cooja/LogScriptEngine.java
- java/org/contikios/cooja/Simulation.java
- java/org/contikios/cooja/serialsocket/SerialSocketServer.java
Only set returnValue upon error. Which error that
is returned is not deterministic, but some error
will always be returned.
> Only pass failing return values to stopSimulation()

- java/org/contikios/cooja/Cooja.java
Fix the broken indentation, and hoist/sink some code outside the try-statement.
> Cooja: fix indentation

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/LogScriptEngine.java
- java/org/contikios/cooja/Simulation.java
- java/org/contikios/cooja/plugins/DGRMConfigurator.java
- java/org/contikios/cooja/plugins/ScriptRunner.java
This parameter is a leftover from the applet support, remove the parameter and use the Cooja frame as parent.
> Cooja: remove fixed method parameter

- java/org/contikios/cooja/EventQueue.java
- java/org/contikios/cooja/SafeRandom.java
These structures are internal to Cooja.
> Reduce visibility of Cooja-internal classes

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/VisPlugin.java
Make removePlugin only remove plugins and put the responsibility of querying the user on VisPlugin instead.
> Cooja: make removePlugin only remove plugins

- java/org/contikios/cooja/script/ScriptParser.java
This makes the builtin code readable.
> ScriptParser: use java textblock for code

- java/org/contikios/cooja/contikimote/ContikiMoteType.java
- java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
- java/org/contikios/cooja/dialogs/ContikiMoteCompileDialog.java
- java/org/contikios/cooja/mote/BaseContikiMoteType.java
- java/org/contikios/cooja/mspmote/MspCompileDialog.java
- java/org/contikios/cooja/mspmote/MspMoteType.java
The dialog wants the Cooja object, so pass
that instead of the simulation.
> AbstractCompileDialog: change signature

- java/org/contikios/cooja/Cooja.java
This will enable further simplifications.
> Cooja: inline single-use method

- java/org/contikios/cooja/Cooja.java
This is a large method so this commit
only contains an inline of the method.
This brings more variables in scope
for the menu/toolbar construction,
so localizations/simplifications
will follow in future commits.
> Cooja: inline createMenuBar

- java/org/contikios/cooja/Cooja.java
Localize fields, inline a single-use method, and simplify from the additional knowledge after inlining.
> Cooja: simplfy startPlugin

- java/org/contikios/cooja/script/ScriptParser.java
Just inline all the methods, the result
will be simplified in a later commit.
> ScriptParser: inline static methods

- java/org/contikios/cooja/GUI.java
- java/org/contikios/cooja/Main.java
The functionality did not belong in the Cooja
class, but it clearly belongs in the GUI class,
so move it there.
> Move setLookAndFeel to GUI

- java/org/contikios/cooja/script/ScriptParser.java
Clean up the code in the constructor after the latest inlining of the static methods.
> Simplify ScriptParser constructor

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/GUI.java
This should have been a part of the commit that created the GUI class.
> Cooja: move showErrorDialog to GUI class

- java/org/contikios/cooja/VisPlugin.java
And use a pattern variable inside the InternalFrameAdapter.
> VisPlugin: make parent final

- java/org/contikios/cooja/GUI.java
- java/org/contikios/cooja/Simulation.java
This is preparation for making seed a final field.
> Tweak simulation initialization

- java/org/contikios/cooja/Cooja.java
This is no longer used, so remove it.
> Cooja: remove PATH_JAVAC

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/Simulation.java
- java/org/contikios/cooja/mspmote/MspMote.java
- java/org/contikios/cooja/radiomediums/DirectedGraphMedium.java
The support for generics in JDOM2
makes the casts redundant.
> Remove casts that are now spurious

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/GUI.java
- java/org/contikios/cooja/Simulation.java
This moves the call of `setConfigXML` from Cooja to Simulation.
> Simulation: complete init in constructor

- java/org/contikios/cooja/GUI.java
- java/org/contikios/cooja/dialogs/AddMoteDialog.java
Have the dialog return the settings
and put the simulation updates inside
GUI. The logic does not really
belong in GUI either, but it is
a better place than in the dialog.
> Move sim logic from AddMoteDialog

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/Simulation.java
Hide the shutdown logic inside Simulation.
> Simulation: tweak shutdown responsibility

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/GUI.java
- java/org/contikios/cooja/Simulation.java
Move the plugin startup code into the Simulation constructor, do some minor tweaks to the existing code, and fix the race condition in the startup that made 17-tun-rpl-br fail sporadically in Contiki-NG.
> Fix race condition in Simulation startup

- java/org/contikios/cooja/plugins/TimeLine.java
Remove the slider for adjusting zoom level, and inline/localize/privatize variables/methods.
> Timeline simplifications

- java/org/contikios/cooja/Cooja.java
Let the remaining tests run even if one test
fails creating its simulation.
> Cooja: make a single call to doQuit

- java/org/contikios/cooja/GUI.java
This method is only called from the AWT
thread.
> GUI: remove RunnableInEDT wrapping

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/GUI.java
The method in GUI is always called from
the AWT thread so move the RunnableInEDT
to Cooja.
> Move RunnableInEDT from GUI to Cooja

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/GUI.java
- java/org/contikios/cooja/Simulation.java
- java/org/contikios/cooja/dialogs/CreateSimDialog.java
This record is only used for the dialog
now, so move it to that class.
> Move SimConfig to CreateSimDialog

- java/org/contikios/cooja/dialogs/SerialUI.java
This removes most of the regexp-work in
a method that is called for every character
received.
> SerialUI: do not log non-printable chars

- java/org/contikios/cooja/contikimote/ContikiMoteType.java
This is an internal implementation detail that should not be exposed to the rest of the world.
> ContikiMoteType: internalize javaClassName

- java/org/contikios/cooja/Cooja.java
Move the update-simulation handling
into go() where the other similar options
are handled.
> Cooja: consolidate option handling

- java/org/contikios/cooja/contikimote/ContikiMote.java
This fixes an IntelliJ warning.
> ContikiMote: use Math.abs instead of unary minus

- java/org/contikios/cooja/serialsocket/SerialSocketServer.java
Do not start the commands when Cooja is updating
simulation files.
> SerialSocketServer: conditionally run cmds

- java/org/contikios/cooja/plugins/Visualizer.java
Localize code, inline single-use methods, and remove commented out code.
> Visualizer: various simplifications

- java/org/contikios/cooja/plugins/TimeLine.java
This PR contains the usage of the ZOOM_LEVELS array to a single method.
> Timeline: preparations for removing ZOOM_LEVELS array

- java/org/contikios/cooja/GUI.java
- java/org/contikios/cooja/Simulation.java
The method does not make sense, so remove
it and update the button/menu logic to work
without it. The fact that the buttons/menus
have been enabled seems to have been related
to timing.
> Simulation: remove isRunnable method

- java/org/contikios/cooja/mspmote/MspMote.java
Loading debug info shows up when profiling
Cooja, so do it lazily to speed up the Contiki-NG
regression tests.
> MspMote: load debug info on-demand

- java/org/contikios/cooja/Cooja.java
This is preparation for making the external
tools handling less stateful.
> Cooja: factor out external tools settings

- java/org/contikios/cooja/Main.java
Add a command line option that decides whether Cooja runs in headless mode. This removes the distinction between -nogui and -quickstart, so Cooja can now
be started in headless mode with
"--no-gui -quickstart=hello.csc".
Picocli can only negate long options, so the --
is required.
> Add a --[no-]gui command line option

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/GUI.java
This is a GUI-specific container so move
it to the GUI class.
> Move menuMotePluginClasses to GUI

- java/org/contikios/cooja/GUI.java
This method always acts on myDesktopPane, so put
that inside the method instead.
> GUI: remove unused parameter

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/GUI.java
Rename methods and push the handling
of the GUI container inside GUI.
> Tweak parseProjectConfig further

- java/org/contikios/cooja/dialogs/ProjectDirectoriesDialog.java
Perform various simplifications. The inlining/lambda-introduction also fixes the indentation.
> ProjectDirectoriesDialog: various simplifications

- java/org/contikios/cooja/GUI.java
Instead of passing in null, put the file
chooser at the caller, and always pass a file
to the load method.
> GUI: put file chooser at call-site

- build.gradle
This is better for performance according to IntelliJ.
> gradle: use configureEach

- java/org/contikios/cooja/contikimote/interfaces/ContikiEEPROM.java
Make the parameter a field of the class instead.
This is preparation for removing Observable.
> ContikiEEPROM: remove fixed parameter

- java/org/contikios/cooja/contikimote/interfaces/ContikiEEPROM.java
This is preparation for removing Observable.
> ContikiEEPROM: convert variables into fields

- java/org/contikios/cooja/contikimote/interfaces/ContikiBeeper.java
Update the label inside doActionsAfterTick()
instead.
> ContikiBeeper: remove use of observer

- java/org/contikios/cooja/contikimote/interfaces/ContikiEEPROM.java
Update the label inside doActionsAfterTick()
instead.
> ContikiEEPROM: remove use of observer

- java/org/contikios/cooja/dialogs/ProjectDirectoriesDialog.java
Keep the logic for identifying and marking
Cooja projects/extensions in the GUI, but
replace the JTree on the left with a JFileChooser
behind an add button instead.
This saves 350 lines of code, and instead
of navigating from the root of the filesystem
and having to expand each level, the dialog
uses the Cooja directory as the starting
directory.
> ProjectDirectoriesDialog: use JFileChooser

- java/org/contikios/cooja/dialogs/ProjectDirectoriesDialog.java
Make the user point out cooja.config instead
of the directory. This saves 50 lines of special
handling code, and gives the user an immediate
hint for what they are meant to select in the dialog.
> ProjectDirectoriesDialog: open cooja.config instead

- java/org/contikios/cooja/contikimote/interfaces/ContikiButton.java
- java/org/contikios/cooja/interfaces/Button.java
There is nothing in the tree that observes
buttons.
> Button: remove observable

- java/org/contikios/cooja/contikimote/interfaces/ContikiCFS.java
Perform the UI updates inside doActionsAfterTick() instead.
> ContikiCFS: remove Observable

- java/org/contikios/cooja/plugins/TimeLine.java
Remove the listener that was added.
> TimeLine: stop leaking listeners

- java/org/contikios/cooja/MoteInterfaceHandler.java
- java/org/contikios/cooja/Simulation.java
Move the looping over interfaces into
the MoteInterfaceHandler.
> MoteInterfaceHandler: add added/removed methods

- java/org/contikios/cooja/Simulation.java
This is preparation for removing the special
simulationFinishedLoading method in the
RadioMedium interface.
> Simulation: config radio medium last

- doc/ChangeLog.md
- java/org/contikios/cooja/MoteType.java
- java/org/contikios/cooja/mote/BaseContikiMoteType.java
- java/org/contikios/cooja/motes/AbstractApplicationMoteType.java
This method is not used by Cooja.
> MoteType: remove setIdentifier

- java/org/contikios/cooja/interfaces/ApplicationRadio.java
This method is always called from the simulation
thread, so put an assert and remove the choice
logic.
> ApplicationRadio: inline Runnable and simplify

- java/org/contikios/cooja/contikimote/interfaces/ContikiRS232.java
- java/org/contikios/cooja/mspmote/interfaces/CC1101Radio.java
- java/org/contikios/cooja/mspmote/interfaces/CC1120Radio.java
- java/org/contikios/cooja/mspmote/interfaces/CC2520Radio.java
- java/org/contikios/cooja/mspmote/interfaces/TrxebLEDs.java
- java/org/contikios/cooja/plugins/Visualizer.java
- java/org/contikios/mrm/MRM.java
- java/se/sics/mspsim/extutil/highlight/HighlightSourceViewer.java
Remove a stack trace printout, commented out code, and do some light reformatting while touching these lines.
> Use lambda

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/GUI.java
- java/org/contikios/cooja/Main.java
- java/org/contikios/cooja/Simulation.java
The seed applies to existing simulations,
the dialog for creating a new simulation
will prompt for the seed.
> Move randomSeed from Config to SimConfig

- java/org/contikios/cooja/GUI.java
Replace the "Status" line with information
about the seed of the simulation.
> GUI: provide seed in sim information

- doc/ChangeLog.md
- java/org/contikios/cooja/Mote.java
- java/org/contikios/cooja/MoteInterfaceHandler.java
- java/org/contikios/cooja/Simulation.java
- java/org/contikios/cooja/motes/AbstractWakeupMote.java
Move the code for adding/removing interfaces
from Simulation to Mote.
> Make the mote add/remove its interfaces

- java/org/contikios/cooja/Watchpoint.java
- java/org/contikios/cooja/WatchpointMote.java
- java/org/contikios/cooja/mspmote/MspMote.java
- java/org/contikios/cooja/mspmote/MspMoteType.java
- java/org/contikios/cooja/mspmote/plugins/BreakpointsUI.java
- java/org/contikios/cooja/mspmote/plugins/CodeUI.java
- java/org/contikios/cooja/mspmote/plugins/MspBreakpoint.java
- java/org/contikios/cooja/util/JSyntaxAddBreakpoint.java
- java/org/contikios/cooja/util/JSyntaxRemoveBreakpoint.java
Use long to represent addresses outside MSPSim.
> Update addresses to long

- java/org/contikios/cooja/interfaces/IPAddress.java
- java/org/contikios/cooja/interfaces/RimeAddress.java
- java/org/contikios/cooja/plugins/skins/AddressVisualizerSkin.java
- java/org/contikios/cooja/util/EventTriggers.java
Replace with EventTriggers that is triggered
at the same times instead.
> Remove observer on addresses

- java/org/contikios/cooja/Simulation.java
- java/org/contikios/cooja/mspmote/plugins/MspCodeWatcher.java
- java/org/contikios/cooja/util/EventTriggers.java
This is in preparation to remove the deprecated Observable.
> Simulation: add listener support for simulation state changes

- java/org/contikios/cooja/MoteInterfaceHandler.java
Reverts contiki-ng/cooja#1062
This does not solve the intended issue.
> Revert "MoteInterfaceHandler: add clock fallback"

- java/org/contikios/cooja/Simulation.java
This is in preparation to remove the deprecated Observable.
> Simulation: add listener support for mote type changes

- java/org/contikios/cooja/GUI.java
- java/org/contikios/cooja/Simulation.java
- java/org/contikios/cooja/mote/BaseContikiMoteType.java
Put the change mote type dialog
in the GUI class, and update
the XML in the same way as the
other simulation reconfiguration.
> Move change mote type to GUI

- java/org/contikios/cooja/Main.java
Since there is only one way to pass files
to Cooja, the code can be simplified
> Main: simplify sim file argument handling

- java/org/contikios/cooja/GUI.java
- java/org/contikios/cooja/Simulation.java
This should have been a part of #1065.
> Move the code for preserving radio medium config

- java/org/contikios/cooja/interfaces/Position.java
- java/org/contikios/cooja/plugins/Visualizer.java
- java/org/contikios/cooja/plugins/skins/PositionVisualizerSkin.java
- java/org/contikios/cooja/radiomediums/LogisticLoss.java
- java/org/contikios/cooja/radiomediums/UDGM.java
Use an event trigger instead of an observable,
and update the clients.
> Position: remove observable

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/GUI.java
- java/org/contikios/cooja/Simulation.java
- java/org/contikios/cooja/VisPlugin.java
- java/org/contikios/cooja/plugins/BaseRSSIconf.java
- java/org/contikios/cooja/plugins/BufferListener.java
- java/org/contikios/cooja/plugins/DGRMConfigurator.java
- java/org/contikios/cooja/plugins/LogListener.java
- java/org/contikios/cooja/plugins/RadioLogger.java
- java/org/contikios/cooja/plugins/TimeLine.java
- java/org/contikios/cooja/plugins/Visualizer.java
This container should have the same lifetime
as the simulation.
> Move mote highlight observer to Simulation

- java/org/contikios/cooja/MoteInterfaceHandler.java
- java/org/contikios/cooja/Simulation.java
Move the radio medium creation code back to
Simulation since it now has a single caller.
> Move radio medium creation to Simulation

- java/org/contikios/cooja/dialogs/MessageListUI.java
- java/org/contikios/cooja/plugins/VariableWatcher.java
- java/org/contikios/cooja/plugins/analyzers/PcapExporter.java
- java/org/contikios/cooja/serialsocket/SerialSocketClient.java
- java/org/contikios/cooja/serialsocket/SerialSocketServer.java
Log some text besides the exception so the user gets more than just a backtrace to read.
> Log more than exception

- java/org/contikios/cooja/Breakpoint.java
- java/org/contikios/cooja/WatchpointMote.java
- java/org/contikios/cooja/motes/AbstractEmulatedMote.java
- java/org/contikios/cooja/mspmote/MspMote.java
- java/org/contikios/cooja/mspmote/plugins/MspBreakpoint.java
This will enable more code sharing between motes that support watchpoints.
> Add Breakpoint class

- java/org/contikios/cooja/contikimote/interfaces/ContikiRadio.java
- java/org/contikios/cooja/interfaces/ApplicationRadio.java
- java/org/contikios/cooja/interfaces/Radio.java
- java/org/contikios/cooja/mspmote/interfaces/CC1101Radio.java
- java/org/contikios/cooja/mspmote/interfaces/CC1120Radio.java
- java/org/contikios/cooja/mspmote/interfaces/CC2520Radio.java
- java/org/contikios/cooja/mspmote/interfaces/Msp802154Radio.java
This is just preparation, there are no listeners
to the triggers, and the old observers continue
to work like before.
> Add event triggers for Radio

- java/org/contikios/cooja/Cooja.java
This is done automatically when removing
a mote.
> Cooja: remove unused method

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/mspmote/plugins/MspCycleWatcher.java
- java/org/contikios/cooja/plugins/EventListener.java
- java/org/contikios/cooja/plugins/MoteInterfaceViewer.java
- java/org/contikios/cooja/plugins/RadioLogger.java
- java/org/contikios/mrm/AreaViewer.java
- java/org/contikios/mrm/FormulaViewer.java
The code at the end of startPlugin() has
this functionality.
> Do not call setSelected from plugins

- java/org/contikios/cooja/Breakpoint.java
- java/org/contikios/cooja/WatchpointMote.java
- java/org/contikios/cooja/motes/AbstractWakeupMote.java
- java/org/contikios/cooja/mspmote/MspMote.java
- java/org/contikios/cooja/mspmote/plugins/MspBreakpoint.java
- java/org/contikios/cooja/util/JSyntaxAddBreakpoint.java
Made some smaller updates of WatchpointMote API
> WatchpointMote: move more watchpoint / breakpoint functionality to AbstractWakeupMote

- doc/ChangeLog.md
- java/org/contikios/cooja/MoteType.java
- java/org/contikios/cooja/contikimote/ContikiMoteType.java
- java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
- java/org/contikios/cooja/mote/BaseContikiMoteType.java
- java/org/contikios/cooja/motes/AbstractApplicationMoteType.java
- java/org/contikios/cooja/motes/DisturberMoteType.java
- java/org/contikios/cooja/motes/ImportAppMoteType.java
- java/org/contikios/cooja/mspmote/Exp5438MoteType.java
- java/org/contikios/cooja/mspmote/MspMoteType.java
- java/org/contikios/cooja/mspmote/SkyMoteType.java
- java/org/contikios/cooja/mspmote/Z1MoteType.java
Change the return type, and two more commits that touches the same lines of code.
> MoteType: make getMoteInterfaceClasses return list

- java/org/contikios/cooja/ExtensionManager.java
- java/org/contikios/cooja/GUI.java
- java/org/contikios/cooja/MoteInterfaceHandler.java
- java/org/contikios/cooja/Simulation.java
Mote types are registered like plugins,
so this functionality belongs in this class.
> Move createMoteType() to ExtensionManager

- java/org/contikios/cooja/Simulation.java
Hoist the loop and the non-GUI code
to outside startPlugin.
This makes it possible to give an
updated message for the progress
for each plugin that is started.
> Simulation: yield from AWT thread

- java/org/contikios/cooja/util/EventTriggers.java
This is more readable in the performance
profile.
> EventTriggers: use a classical loop

- java/org/contikios/cooja/dialogs/SerialUI.java
Make a local method instead of using
a predicate from a regular expression.
> SerialUI: optimize punctuation check

- java/org/contikios/cooja/interfaces/MoteAttributes.java
- java/org/contikios/cooja/plugins/skins/AttributeVisualizerSkin.java
- java/org/contikios/cooja/util/EventTriggers.java
Add a MoteAttributeData in preparation for passing processed information to the consumers.
> MoteAttributes: remove observer

- java/org/contikios/cooja/plugins/TimeLine.java
Also, initialize minimal event width menu items with current value from start.
> TimeLine: code simplification and cleanup

- java/org/contikios/cooja/radiomediums/AbstractRadioMedium.java
This is preparation for removing observers.
> AbstractRadioMedium: initialize observer in constructor

- java/org/contikios/cooja/Cooja.java
This makes the failure dialog less wide,
so the close button can be seen.
> Cooja: remove one "Unknown error: "

- build.gradle
- doc/ChangeLog.md
- java/org/contikios/cooja/Main.java
Add a --platform parameter and start
MSPSim when that parameter is passed.
> Main: integrate MSPSim Main

- java/org/contikios/cooja/mspmote/MspMote.java
These are not required for regular use.
> MspMote: replace checks with asserts

- java/org/contikios/cooja/Cooja.java
Failed tests are hard to spot in the Contiki-NG
tests, so print them all at the end of the run.
> Cooja: print all failed tests at end

- java/org/contikios/cooja/contikimote/ContikiMoteType.java
This saves 1 iteration of parsing of the readelf
output on Linux, which translates to ~10% reduction in memory allocation on
27-cooja-rpl-tsch-orchestra-root-rule-storing.
> ContikiMoteType: do single pass over data

- java/org/contikios/cooja/radiomediums/DestinationRadio.java
- java/org/contikios/cooja/radiomediums/DirectedGraphMedium.java
This fixes an issue with missing constructor.
> DirectedGraphMedium: update configuration to support new API

- java/org/contikios/mrm/MRM.java
This seems to have been unused since 2011.
> MRM: remove unused variable

- java/se/sics/mspsim/util/ELF.java
IntelliJ gives a warning for these lines,
so stop incrementing the counter on
the last read.
> ELF: remove unused post-inc result

- java/se/sics/mspsim/platform/jcreate/JCreateNode.java
- java/se/sics/mspsim/platform/sentillausb/SentillaUSBNode.java
- java/se/sics/mspsim/platform/sky/SkyNode.java
- java/se/sics/mspsim/platform/sky/TelosNode.java
This enables making some more variables final.
> MSPSim: move setupNodePorts to constructors

- java/se/sics/mspsim/core/Chip.java
- java/se/sics/mspsim/core/MSP430.java
- java/se/sics/mspsim/core/MSP430Core.java
- java/se/sics/mspsim/platform/GenericNode.java
- java/se/sics/mspsim/platform/ti/CC430Node.java
- java/se/sics/mspsim/util/ComponentRegistry.java
- java/se/sics/mspsim/util/IHexReader.java
- java/se/sics/mspsim/util/Test.java
Push code around so it is executed in the constructor instead of sometime later. This enables making some fields final right now, and should pave the way for more.
> MSPSim: make some fields final

- java/se/sics/mspsim/platform/wismote/WismoteGui.java
Pass the height to the height parameter,
and width to the width parameter.
> WismoteGui: fix order of parameters

- java/se/sics/mspsim/ui/StackUI.java
This code has been commented out since 2008.
> StackUI: remove commented out code

- java/se/sics/mspsim/util/ConfigManager.java
Inline single-use methods and reduce visibility of loadConfiguration.
This clarifies what parts of ConfigManager that are still used, and which are not.
> Reduce interface of ConfigManager

- java/org/contikios/cooja/mspmote/interfaces/MspSerial.java
- java/org/contikios/mrm/AngleInterval.java
- java/org/contikios/mrm/ChannelModel.java
- java/org/contikios/mrm/Interval.java
Use ArrayList as container, List
as interface.
> Replace some Vectors

- java/org/contikios/cooja/Main.java
- java/se/sics/mspsim/Main.java
- java/se/sics/mspsim/platform/GenericNode.java
Start preparing for passing the firmware
to the constructor, instead of finding
it and setting things up much later.
> Move parameter validation to main

- java/org/contikios/cooja/mspmote/MspMote.java
- java/se/sics/mspsim/platform/GenericFlashNode.java
- java/se/sics/mspsim/platform/esb/ESBNode.java
- java/se/sics/mspsim/platform/jcreate/JCreateNode.java
- java/se/sics/mspsim/platform/sentillausb/SentillaUSBNode.java
- java/se/sics/mspsim/platform/sky/CC2420Node.java
- java/se/sics/mspsim/platform/sky/MoteIVNode.java
- java/se/sics/mspsim/platform/ti/CC430Node.java
- java/se/sics/mspsim/platform/ti/Exp1101Node.java
- java/se/sics/mspsim/platform/ti/Exp1120Node.java
- java/se/sics/mspsim/platform/ti/Exp5438Node.java
- java/se/sics/mspsim/platform/ti/Trxeb1120Node.java
- java/se/sics/mspsim/platform/ti/Trxeb2520Node.java
- java/se/sics/mspsim/platform/tyndall/TyndallNode.java
- java/se/sics/mspsim/platform/wismote/WismoteNode.java
- java/se/sics/mspsim/platform/z1/Z1Node.java
A bunch of commits to prepare for adding an abstract class GenricFlashNode, and then adding/using it. Move out some additional code from setupNode() after that as preparation for more code sharing.
> MSPSim: add GenericFlashNode

- java/org/contikios/mrm/ChannelModel.java
Add the missing enum values to stop
throwing exceptions from getDescription.
> ChannelModel: make getDescription() total

- java/se/sics/mspsim/platform/GenericNode.java
- java/se/sics/mspsim/util/IHexReader.java
Also add a commit that inlines a single-use method in GenericNode at the end of this PR to avoid conflicts.
> IHexReader: simplify & modernize

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/Simulation.java
Started plugins are kept track in the simulation,
so move the code for extracting their config
into simulation as well.
> Move plugin config extract to Simulation

- build.gradle
Follow the Gradle documentation for reproducible
archives:
https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives
> build.gradle: set reproducible archives

- doc/ChangeLog.md
- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/dialogs/AbstractCompileDialog.java
- java/org/contikios/cooja/mote/BaseContikiMoteType.java
- java/org/contikios/cooja/mspmote/plugins/MspCodeWatcher.java
This makes csc files portable between Linux and
macOS.
> Expand $(MAKE) in csc files

- .github/workflows/build.yml
This adds a basic sanity check of
Cooja functionality for ContikiMoteTypes.
> CI: run 07-simulation-base in CI

- java/org/contikios/cooja/radiomediums/AbstractRadioMedium.java
- java/org/contikios/cooja/radiomediums/DirectedGraphMedium.java
- java/org/contikios/cooja/radiomediums/LogisticLoss.java
- java/org/contikios/cooja/radiomediums/UDGM.java
- java/org/contikios/mrm/MRM.java
The source channel is constant, so get that
once outside the loop.
> radiomediums: hoist variable from loop

- java/org/contikios/cooja/Cooja.java
- java/org/contikios/cooja/contikimote/ContikiMoteType.java
Put the regexp where it is used instead of various other places in the source code.
> ContikiMoteType: simplify CommandSectionParser

- java/org/contikios/cooja/contikimote/ContikiMoteType.java
Issue identified by kkrentz in #1343.
> ContikiMoteType: fix readelf 2.39 issue

- java/org/contikios/cooja/motes/DisturberMoteType.java
The original disturber starts as soon as created, has hard coded timing parameters, and cannot be paused / restarted.
This pull request adds a number of public methods to the disturber mote type to allow the user to perform on/off control and adjust the timing parameters.
> Enhanced disturber mote with on/off control and adjustable duty cycle

- java/se/sics/mspsim/cli/CommandHandler.java
- java/se/sics/mspsim/cli/MiscCommands.java
- java/se/sics/mspsim/util/ComponentRegistry.java
This avoids the casting and prepares for
using native-image out of the box with
Cooja.
> ComponentRegistry: return list-type
